### ISSUE TITLE
Support XSRF mitigation in the CookieAuth middleware

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#100]
Form Posts are vulnerable to XSRF attacks because they can be sent without user interaction and automatically include the users cookies.

Proposal: Have the cookie auth middleware check for the anti-forgery token in form posts. If it's missing then do not set the user on the request.
Flow:
- Check for an auth cookie
- Deserialize and valid the cookie
- Check if it is a POST request with a form content-type
- Notification - ValidateAntiforgeryToken with a default implementation that:
 - Reads the request body and looks for an anti-forgery token
 - If one is found, continue normally, otherwise do not set the user on the request, let it pass through as anonymous.
 - The notification is intended as a hook where you could selectively enforce the policy per request, or customize the validation procedure. The notification should take the user as an input parameter.

**Comment by Eilon** [comment]
We're not planning to do any further work to do here because all the antiforgery features are now in a reusable component located here: https://github.com/aspnet/AntiForgery

It would still be up to a developer to hook this up themselves, but we do have all the right utilities to make it fairly easy to implement.
