### ISSUE TITLE
OIDC TokenValidated event fires in a different order depending on the flow

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1027]
The OIDC TokenValidated event fires in a different order based on the flow you're using.
1) for id_token it fires  first / alone
2) for code flow it fires after TokenResponseReceived
3) for code+id_token it fires before the code is redeemed, but then there's no event fired after the second id_token from token endpoint is validated

Proposal (Breaking):
Rename TokenValidated to something authorization endpoint specific like AuthorizationEndpointIdTokenValidated. Then add a new event TokenEndpointIdTokenValidated. Now the order would not vary, only the events based on your flow.

**Comment by Eilon** [comment]
For case (3) we should fire the event twice, and on the second time add the additional info.

**Comment by Tratcher** [comment]
I'm still concerned that firing the same event for two different scenarios will confuse and break people. The first time it fires it's primarily a chance for people to do additional validation and claims transformation. The new case we're considering is very different, it's about reconciling a secondary token/principal.

New proposal:
Keep TokenValidated as is for the first token processed, the app's implementation isn't likely to vary based on the endpoint the token was received from. Existing apps will be un-effected.
Add a new event SecondaryTokenValidated that only fires if a second token is received (code+id_token). This event presents both sets of tokens and principals and allows the user to reconcile them (see #1028).

**Comment by muratg** [comment]
We'll potentially punt this if we can't get this in by early next week.

**Comment by Tratcher** [comment]
@PinpointTownes any thoughts on adding an additional event here:
https://github.com/aspnet/Security/blob/824539f47ac7f57a824092b04795e25198e1438f/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L666-L673
As described in https://github.com/aspnet/Security/issues/1027#issuecomment-263073109

See https://github.com/aspnet/Security/issues/1028 about reconciling the two tokens.

**Comment by PinpointTownes** [comment]
Sounds like a good idea, fairly cheap to implement and with no chance of breaking existing apps, no?

**Comment by Tratcher** [comment]
Yes, it should be easy enough. The main question is how useful is that second token.

**Comment by PinpointTownes** [comment]
> The main question is how useful is that second token.

Currently, the access/refresh/identity tokens returned from the token endpoint are always preferred to the ones directly extracted from the authorization response. It makes sense in the hybrid flow because the access token retrieved from the token endpoint potentially grants access to more resources than the first one (because you can perform client authentication with backchannel calls, so you're almost sure the caller is really the client app it pretends to be).

For similar reasons, I'm tempted to think that an identity token extracted from the token response message may contain more (sensitive) claims, tho' it's really implementation-specific.

In both cases, preserving the tokens extracted from the authorization responses doesn't seem that interesting, but I presume there's a demand for that? (otherwise you'd probably not consider adding a new event).

**Comment by Tratcher** [comment]
This is an item I filed because we know there's a gap. There haven't been any external requests for it. That's why I asked.

**Comment by Eilon** [comment]
Closing because there doesn't seem to be sufficient consensus on how to fix this and also whether it's even super important.
