### ISSUE TITLE
Any plans to support Basic (aka header) authentication for the /token endpoint in the OIDC middleware?

### ISSUE THREAD

**Issue by rlondner** [aspnet/Security#1032]
Hello,

At this stage, POST authentication seems to be hardcoded in the OIDC middleware (cf. https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L713), even though the OAuth 2.0 spec mentions at https://tools.ietf.org/html/rfc6749#section-2.3.1 that 

"The authorization server MUST support the HTTP Basic authentication scheme for authenticating clients that were issued a client password"

which would be the case for a web app.

Is there any reason why you only implemented the POST authentication method in the RedeemAuthorizationCodeAsync method?

**Comment by Tratcher** [comment]
Are there any specific servers that actually support basic auth on the token endpoint? We haven't seen any requests for this before now.

**Comment by raphaellondner-okta** [comment]
At the very least, identityServer3 seems to support it: https://github.com/IdentityServer/IdentityServer3/blob/93bc6bc9b536146b9e3fa0bed21d77283d07f788/source/Core/Endpoints/Connect/DiscoveryEndpointController.cs#L147

And I wouldn't be surprised that many other OAuth-compliant providers do support it as well (after all, it's mandatory as per the OAuth 2.0 spec)

**Comment by PinpointTownes** [comment]
> Are there any specific servers that actually support basic auth on the token endpoint?

If you like numbers: of the 36 OAuth2 providers we have in aspnet-contrib, 3 only support basic authentication: FitBit, Yahoo and Reddit.

**Comment by Tratcher** [comment]
Thanks @PinpointTownes, do any of them require it?

Any idea why a server would want to support/require basic? So it could validate the request without reading the body?

**Comment by PinpointTownes** [comment]
@Tratcher woops, sorry, maybe I wasn't clear: FitBit, Yahoo and Reddit only support basic authentication (if you try to flow the client credentials in the request body, it will fail).

**Comment by raphaellondner-okta** [comment]
@Tratcher maybe because the OAuth spec makes it mandatory? (cf. https://tools.ietf.org/html/rfc6749#section-2.3.1).

@PinpointTownes Thanks for the clarification. I gues the interesting question is: out of those 32 OAuth providers, are there any that don't support basic authentication?

**Comment by Tratcher** [comment]
@raphaellondner-okta that wasn't the question. What is the benefit of using basic over putting the credentials in the body?

**Comment by raphaellondner-okta** [comment]
@Tratcher It seems that you asked why an authorization server would want to support basic auth on the token endpoint, and my answer is the spec's answer: because it MUST do so.

Furthermore, the spec clearly mentions that it should be the recommended method, when available, to exchange the auth code for the OIDC and/or OAuth tokens. So a spec-compliant library should at the very least implement Basic Auth on the token endpoint (without resorting to a custom override of the AuthorizationCodeReceived event). Don't you agree?

I can't tell much about the benefit of using Basic over Post, but I would guess that the OAuth spec writers had some security concerns in mind (probably would be worth asking them?)

**Comment by PinpointTownes** [comment]
@raphaellondner-okta good question, I don't remember the exact number, but I'll take a look.

> What is the benefit of using basic over putting the credentials in the body?

Though it's the client authentication mode recommended by the OAuth2 spec (and the "default" mode in OIDC), basic authentication has important downsides: many HTTP servers treat the request headers as ASCII-encoded strings so you can't use "special chars" in your client credentials and you can't can't use `:` as it's used as the separator.

The only benefit I can find is that it's supposed to be implemented everywhere, as @raphaellondner-okta said.

In practice, most people use the `client_id`/`client_secret` parameters as they are easier to use and much more robust. AFAIK, there's no security concern when using `client_secret_post` (the only thing prevented by the spec' is flowing the credentials via the query string, for obvious reasons)

**Comment by PinpointTownes** [comment]
Speaking of client authentication modes, here's a related ticket: https://github.com/aspnet/Security/issues/701.

**Comment by Eilon** [comment]
Closing because this seems to have limited usefulness and we are not planning to implement this.

**Comment by raphaellondner-okta** [comment]
It's interesting that Microsoft is not willing to implement something mandated by the OAuth 2.0 spec (and which, quite frankly, shouldn't be that difficult), but so be it.

That being said, what is your recommendation to use this library with FitBit, Reddit and Yahoo?
https://dev.fitbit.com/docs/oauth2/#access-token-request
https://github.com/reddit/reddit/wiki/OAuth2#retrieving-the-access-token
https://developer.yahoo.com/oauth2/guide/flows_authcode/#step-4-exchange-authorization-code-for-access-token

Use a different .NET library, maybe?

**Comment by Tratcher** [comment]
There are implementations available for those over here:
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/src/AspNet.Security.OAuth.Fitbit/FitbitAuthenticationHandler.cs#L66

**Comment by jdmichel** [comment]
This just cost our company an embarrassing amount of time and money to track down. It's mandated as optional in the OAUTH 2.0 spec, but required by the OIDC spec. Your current implementation isn't even allowed by the OIDC spec. 
And you knew about this BUG a year and a half ago?
The point of having a spec is that each implementer doesn't a get a vote about what they think makes sense for one reason or another. We implement a spec so that all the different solutions will be interoperable. For once, someone actually makes one of those rare and precious specs that isn't ambiguous and open to interpretation, and then your team decides to ignore it anyway. 
<sigh>
