### ISSUE TITLE
Proposal: Allow the OpenIdConnectHandler to care about refreshTokens

### ISSUE THREAD

**Issue by glatzert** [aspnet/Security#1048]
My website is communication with a web-API, which is accessed via OAuth-Bearer-Authentication.
To cope with the AccessTokens and RefreshTokens, I pulled ADAL into my project, which has a rather impractical interface for it's Token-Caching and manipulation of that cache - espacially for webserver <-> webserver scenarios.

So I'd propose to pull the RefreshToken Handling into the OpenIDConnectHandler, to ensure, that AccessTokens are refreshed automatically.

**Comment by Tratcher** [comment]
The handler can't do automatic token refresh because it only runs during the initial login. The handler also doesn't have a direct reference to the stored tokens, they're stored in the auth cookie.

There are two ways to do auto refresh:
1) as a background task on the server. This requires storing the tokens in a persistent store that the server always has access to even without active requests (as opposed to the auth cookie).
2) checking the token on each request/use. The OIDC handler doesn't run on each request, only the CookieAuth middleware does that. For example you would check the token expiration before using it in an MVC Controller, or in the CookieAuth OnValidatePrincipal event.

**Comment by Eilon** [comment]
There are no plans at this time to implement automatic processing of refresh tokens in ASP.NET Core.
