### ISSUE TITLE
UseOpenIdConnectAuthentication: Signature validation failed

### ISSUE THREAD

**Issue by tokadu** [aspnet/Security#1085]
I'm using OpenAM Forgerock with the following options:

```c#
new OpenIdConnectOptions
            {
                // Note: setting the Authority allows the OIDC client middleware to automatically
                // retrieve the identity provider's configuration and spare you from setting
                // the different endpoints URIs or the token validation parameters explicitly.
                Authority = "https://XXXXX.com/openam",
                ClientId = "oidc-testapi-math",
                ClientSecret = "password",

                AuthenticationMethod = OpenIdConnectRedirectBehavior.RedirectGet,
                AuthenticationScheme = "oidc",

                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                RequireHttpsMetadata = false,
                SaveTokens = true,

                CallbackPath = new PathString("/signin-oidc"),

                PostLogoutRedirectUri = "https://tokudacoreweb20161212013346.azurewebsites.net/",

                ResponseType = "code token id_token",

                MetadataAddress = "https://XXXXX.com/openam/oauth2/.well-known/openid-configuration",

                GetClaimsFromUserInfoEndpoint = true,
...
```

The Jwt oken validation fails with:

IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey , KeyId: zhBofbZw+jkZZjXs28fGfzxZgM8=
'.
Exceptions caught:
 ''.
token: '{"alg":"HS256","typ":"JWT"}.{"at_hash":"YKNtDasu4WqJCpjN333MIg","sub":"q_00890","auditTrackingId":"53be3f0c-7663-47ba-84b2-29ce9dfabbf3-8507","iss":"https://XXXXX.com:443/openam/oauth2","tokenName":"id_token","nonce":"636200184414741298.YmVhMzFkYjctZTY0MC00MGE4LWIxODEtNjJmMzlkMTg1OTA2ODBkMGJlMmMtMGJhNC00OTRkLWFjYzctMjBkOWUwZDU5Mjdj","aud":"oidc-testapi-math","c_hash":"4zDY4yWbNT4n8FbztyQ8Ow","org.forgerock.openidconnect.ops":"59c13da5-555e-4a2e-abab-8204d0302412","azp":"oidc-testapi-math","auth_time":1484421653,"realm":"/","exp":1484425257,"tokenType":"JWTToken","iat":1484421657}'.
Any ideas what is wrong here ?

**Comment by PinpointTownes** [comment]
> Any ideas what is wrong here ?

Your token is "signed" using a "symmetric signature" algorithm (_to be exact, it's not signed, it's HMACed_). 

In this case, since there's no way for the OpenID Connect middleware to retrieve the signing key from the JWK endpoint, you have to register it manually via `OpenIdConnectOptions.TokenValidationParameters.IssuerSigningKey`.

Alternatively, you could (**and even should**!) update your OpenID Connect provider settings to use a symmetric algorithm like RSA or ECDSA.

If you really want to use HMAC, don't miss this critical security advisory: https://github.com/aspnet/Security/issues/1085

**Comment by Eilon** [comment]
What @PinpointTownes said.
