### ISSUE TITLE
Allow controlling which tokens are saved when SaveTokens is true on OpenIdConnectMiddleware

### ISSUE THREAD

**Issue by akamud** [aspnet/Security#1101]
Some browsers limit the cookie size (related to #830), so we have to be very picky on what gets stored in cookies. In my case, the most size consuming values were the `id_token` and `access_token`. I wanted to store the `refresh_token` and the `access_token`, but I did not want to store de `id_token`, doing this would exceed the 4k cookie size limitation.

So I stopped using the `StoreTokens` option and had to do it all manually in my `OpenIdConnectEvents` getting them from the `OpenIdConnectMessage`.

My suggestion is to have an option to specify exactly what tokens we want to store when using `StoreTokens`.

Something like a `StoredTokensOptions` that could be configured when setting up the `OpenIdConnectMiddleware`.

What do you think?

**Comment by Tratcher** [comment]
At a certain point there are just too many knobs. Using the events for fine grained control is your best option.

**Comment by Tratcher** [comment]
Have you tried using the cookie ITicketStore to mitigate client cookie size issues? https://github.com/aspnet/Security/blob/dev/samples/CookieSessionSample/Startup.cs

**Comment by akamud** [comment]
We were thinking about using `MemoryCache` but I did not know that it was so simple to change the Cookie store mechanism.

About the original subject, even though we fixed this problem using the Events, it was just a suggestion/request for change.

Do you think it can get too complicated for a small win? I'm not sure how many people would actually need that.

**Comment by Eilon** [comment]
Given that there are some ways to do this today, we are not planning to add new functionality for this specific behavior.

**Comment by pierslawson** [comment]
I have tried to find a good way to use the events to prevent the access_token and refresh_token being saved into the cookie as I don't need them there. I can set the Refresh Token to null in the OnTokenResponseReceived handler and it doesn't get saved to the cookie. However, if I do the same with the Access Token, the ValidateTokenResponse method raises an error:

> IDX10336: Both 'id_token' and 'access_token' should be present in OpenIdConnectProtocolValidationContext.ProtocolMessage received from Token Endpoint. Cannot process the message.

Because there are no more events raised between the call to ValidateTokenResponse and SaveTokens, there are no more opportunities to change what is actually saved.

I'm trying to avoid saving the Access Token and the Refresh Token for two reasons:

- It makes the cookie larger than necessary
- It exposes the tokens to the browser (albeit encrypted) and I thought that one of the reasons for using Hybrid flow was to avoid sending these tokens around via the browser

So having "just one more knob" to control this would be nice... or better still an event that could be used to manipulate the tokenEndpointResponse just before it is saved.

**Comment by Tratcher** [comment]
@pierslawson rather than trying to remove the ones you don't want, how about turning off SaveTokens and then adding the tokens you do want? SaveTokens isn't doing anything special.
https://github.com/aspnet/Security/blob/ad425163b29b1e09a41e84423b0dcbac797c9164/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L833

**Comment by pierslawson** [comment]
@Tratcher That would be a good idea except there doesn't seem to be an event to hook into around the point that SaveTokens is executed... I can see a call to run an event on authentication failure (RunAuthenticationFailedEventAsync) but no equivalent for a success.

**Comment by Tratcher** [comment]
@pierslawson Which flow are you using? Code, Code&IdToken, IdToken? You should be able to use TokenValidated or TokenResponseReceived.

**Comment by pierslawson** [comment]
@Tratcher I'm using Code&IdToken. My impression from reading the code was that those events might be called too early in the process. I wasn't sure that the information that I want to save into a cookie (the IdToken) and the data I want to save server side (the RefreshToken) would be available and correctly be populated. I have to admit, it started to get too hard to figure out by just following the code on GitHub at that point (getting it all running in a debugger would help). However, I ran out of time to try and figure out the ideal solution.

**Comment by Tratcher** [comment]
TokenResponseReceived should work then, or UserInformationReceived if you have GetClaimsFromUserInfoEndpoint turned on.

**Comment by leastprivilege** [comment]
;) or - or - or... that's exactly the point.

Persisting those artifacts is such a common thing to do - maybe there should be an event where they are all available at the same time.
