### ISSUE TITLE
Recommended approach for Web Api authentication

### ISSUE THREAD

**Issue by siberianguy** [aspnet/Security#1166]
Visual Studio doesn't have a scaffolding for Web Api authentication (I"ve heard it's planned for release 1.2) but as I know IdentityServer will be a recommended approach. Does it mean IdentityServer4 samples is pretty much what we eventually will see as part of Visual Studio scaffolding?

**Comment by Eilon** [comment]
cc @danroth27

**Comment by danroth27** [comment]
IdentityServer4 is certainly a great option if you're looking for flexible solution with very complete protocol support. We link to their docs from here: https://docs.microsoft.com/aspnet/core/security/authentication. We don't plan to ship IdentityServer4 with VS, but in the future we plan to enable integration of [dotnet new](https://blogs.msdn.microsoft.com/dotnet/2017/04/02/how-to-create-your-own-templates-for-dotnet-new/) based templates with VS so that community templates can easily show up in VS as well.

As part of ASP.NET Core 2.0 we are working on a more opinionated identity service implementation that will align with our other identity offerings (Azure AD B2C, Microsoft Authentication Library) and support Web API security. Hopefully we will have more to share about this new project soon!

@vibronet

**Comment by leastprivilege** [comment]
To expand on that - both libraries will promote the "right" authentication architecture style which is the logical (and maybe also physical) separation of authentication and the business application.

IdentityServer is a full [featured](https://identityserver4.readthedocs.io/en/release/), officially [certified](https://openid.net/certification/) implementation of OpenID Connect and OAuth 2 (and the relevant satellite [specs](https://identityserver4.readthedocs.io/en/release/intro/specs.html)) that you can combine with an arbitrary user store (including ASP.NET Identity) and UI/workflow.

Microsoft's offering will be a more lightweight, less features, less extensibility version of that which is solely based on ASP.NET Identity. But it will include an easy upgrade path to a commercial cloud offering like B2C.

We will publish a detailed feature comparison once it is released.

**Comment by siberianguy** [comment]
Thanks for the clarification. Seems like IdentityServer4 is the way to go for now.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
