### ISSUE TITLE
Azure AD session expires after one hour

### ISSUE THREAD

**Issue by DineshMuralitharan** [aspnet/Security#1177]
I have used Azure AD login using openid connect authentication in my website. The session expires every one hour, and the user is logged out. I saw a solution in the below link to use 

> UseTokenLifetime = false

https://github.com/aspnet/Security/issues/147

Will this fix my issue? or is there any other way to increase expiration time of the session?

**Comment by Tratcher** [comment]
Yes, you should use that option. Did you try it?

**Comment by DineshMuralitharan** [comment]
yes i tried it. 

Please find the following cases,
1. When i navigate between the pages, everything works fine. 
2. When i work on the same page for 1 hour or leave the page idle , then the session is expired and redirects me back to my login page. 

This is the code i have used,

> public void ConfigureAuth(IAppBuilder app)
>         {
>             app.UseKentorOwinCookieSaver();
>             app.UseCookieAuthentication(new CookieAuthenticationOptions());
>             app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
>             app.UseOpenIdConnectAuthentication(
>                 new OpenIdConnectAuthenticationOptions
>                 {
>                     ClientId = clientId,
>                     Authority = authority,
>                     PostLogoutRedirectUri = postLogoutRedirectUri,
>                     RedirectUri = postLogoutRedirectUri,
>                     UseTokenLifetime = false,
>                     Notifications = new OpenIdConnectAuthenticationNotifications
>                     {
>                         AuthenticationFailed = context =>
>                         {
>                             if (context.Exception.Message.StartsWith("OICE_20004") || context.Exception.Message.Contains("IDX10311"))
>                             {
>                                 context.SkipToNextMiddleware();
>                                 context.Response.Redirect("/dashboard");
>                                 return Task.FromResult(0);
>                             }
> 
>                             return Task.FromResult(0);
>                         }
>                     }
>                 });
>         }

**Comment by Tratcher** [comment]
Oh, you're using the old Microsoft.Owin stack. That shouldn't change the expected behavior. When you're active you benifit from CookieAuth's default SlidingExpiration option (https://github.com/aspnet/Security/blob/2d7cd6038fea34b84084685648ac9d0c97be610b/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs#L92-L96).  However disabling UseTokenLifetime should extend you to CookeAuth's default lifetime of 14 days.

What does your Set-Cookie header look like?

As a side note, I do not recommend UseKentorOwinCookieSaver. See https://github.com/aspnet/AspNetKatana/wiki/System.Web-response-cookie-integration-issues#workarounds and https://github.com/aspnet/AspNetKatana/commit/49b78c0874587832e01ba8cad23d9ce8e4f78f19

**Comment by DineshMuralitharan** [comment]
![image](https://cloud.githubusercontent.com/assets/18349782/25046619/0fe059ca-2150-11e7-8e0e-5379421b268a.png)


As a side note, I do not recommend UseKentorOwinCookieSaver - Thanks for letting me know. i will consider this.
