### ISSUE TITLE
Remove display name for OIDC

### ISSUE THREAD

**Issue by danroth27** [aspnet/Security#1185]
Is there really a good reason to specify a display name for OIDC? Can we make the default extension method for adding OIDC not do that and specify null? I don’t think a generic display name of OpenIdConnect is all that useful. You really need to know which authority you are talking to.

**Comment by Tratcher** [comment]
It's better to show a generic name than to not show up at all, no?

**Comment by HaoK** [comment]
Why don't you use the authority name as the scheme instead of the default so it doesn't show up as openidconnect.

**Comment by danroth27** [comment]
In my case I don't want it to show up at all because the OIDC provider is in the app. 

When would the display name "OpenIDConnect" ever be helpful?

**Comment by Eilon** [comment]
Talked to @danroth27 and this shows up in the IdentityService side of the house (the code that's in the MVC Area) because it "leaks over" from the main app's usage of OIDC to connect *to* the IdentityService.

Ideally we would make the OIDC auth provider visible to only the main app and not to the IdentityService, but there might not be a good way to do that.

Right now this is just worked around in the template code by clearing the name.

**Comment by Eilon** [comment]
Given that in https://github.com/aspnet/Security/issues/1186 we will make it easier to clear out the name, we feel it isn't worth adding anything special here. This is a slightly unusual scenario to begin with because the OIDC client and server are one and the same.
