### ISSUE TITLE
PolicyEvaluator.AuthenticateAsync should not set a principal on the HttpContext

### ISSUE THREAD

**Issue by javiercn** [aspnet/Security#1341]
Evaluating a policy should not change the user in the HttpContext.
It essentially prevents the PolicyEvaluator from being used to compute a Principal based on a given policy without changing the principal on the HttpContext.
Setting the principal on the HttpContext should always be the responsibility of the framework/user evaluating a policy,

**Comment by davidfowl** [comment]
Agreed. Can we still make that change though? It's too late.

**Comment by javiercn** [comment]
@davifowl Sadly I believe we can't, but maybe we can come up with something to allow for the scenario

**Comment by HaoK** [comment]
Yeah breaking change to change the default behavior in 2.1, but we can always add a flag/option to disable manipulating the context.User, 

`services.AddAuthorizationPolicyEvaluator(o => o.SetHttpContextUser = false);`

Today there's no options, we could also make AuthZ mimic Authentication with a builder in 2.1...

`services.AddAuthorization().AddPolicyEvaluator(o => o.SetHttpContextUser = false);`

**Comment by leastprivilege** [comment]
> Yeah breaking change to change the default behavior in 2.1,

This is unacceptable.

Can you please elaborate what *exactly* is broken? tbh - things like this make it harder and harder to recommend any of your stuff.

**Comment by HaoK** [comment]
Nothing is broken in normal MVC/SignalR usage scenarios, the new shared IPolicyEvaluator that MVC's authorize filter users takes care of setting HttpContext.User when the policy specifies one.  There's no way to opt out/control that behavior right now.  Although I actually did bring up this issue when added this, (see https://github.com/aspnet/Mvc/pull/6288#discussion_r117326571), since this mostly grew out of just trying to share code between MVC/SignalR, I just didn't think about the external usages or I would have went with having the SignalR/MVC set the User instead.  

But since this behavior is only an issue outside of the MVC authorize filter, these other callers could workaround this issues just by duplicating the logic in the evaluator https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authorization.Policy/PolicyEvaluator.cs#L49 and just removing the two `context.User = ` lines, its not a ton of code.

We can add the ability to control setting the user in a non breaking way, but the frameworks in 2.0 are currently expecting the policy evaluator to set the context.User if needed.

**Comment by leastprivilege** [comment]
I really hope you guys stop making subtle changes to the security system
with every release.


-------
Dominick Baier

**Comment by davidfowl** [comment]
It's not *that* big of a deal so we should really do nothing here and live with the behavior.

**Comment by leastprivilege** [comment]
I don't agree - calling something that evaluates a policy has a side effect of changing the current user. I think this is pretty unexpected behavior that can lead to subtle security problems.

**Comment by davidfowl** [comment]
So you don't want us to make a breaking change in 2.1 but we should fix it in 2.0 before we release. I don't think it meets to bar honestly but we can let others decide.

/cc @DamianEdwards @Eilon

**Comment by HaoK** [comment]
Its not really unexpected, it even states that's what it does in the doc comments

**Comment by leastprivilege** [comment]
OK then.

I personally agree with @javiercn 

> Setting the principal on the HttpContext should always be the responsibility of the framework/user evaluating a policy.

**Comment by davidfowl** [comment]
We all agreed. The discussion was more about what we can do now.

**Comment by geirsagberg** [comment]
I think I may have run into this issue, see https://stackoverflow.com/questions/45462730/how-can-i-replace-httpcontext-user-in-asp-net-core-after-authorization.

What is the recommended workaround to keep the principal unchanged in 2.0 preview 2?

**Comment by geirsagberg** [comment]
Turns out my problem was due to specifying the authentication scheme in the `AuthorizationPolicyBuilder`; once I removed that, the principal remains unchanged.
