### ISSUE TITLE
One or more projects are incompatible with .NETFramework,Version=v4.6.1 (win7-x86)

### ISSUE THREAD

**Issue by dzhelev** [aspnet/Security#1365]
Hey.
I apologize in advance but what do I have to do to build the code?

I have downloaded the zip, opened it in VS2017 and it just fails to build with alot of errors but I guess the underlying problem is one of those:

One or more projects are incompatible with .NETFramework,Version=v4.6.1 (win7-x86).
One or more packages are incompatible with .NETCoreApp,Version=v2.0 (win7-x86).

What am I doing wrong?

**Comment by davidfowl** [comment]
- You need the latest VS2017 preview.
- You need to run `build.cmd` at least once to acquire the version of the dotnet SDK that we use to build projects.
- Once you build you should have a version of dotnet in `%USERPROFILE%\.dotnet\x64`.
- You need to change your PATH environment variable to add `%USERPROFILE%\.dotnet\x64` before. Here's what mine looks like:
![image](https://user-images.githubusercontent.com/95136/29248007-9c908334-7fc1-11e7-879d-846718c70a50.png)

I changed the system path, but you can do it in your powershell window. Note, if you do it in your powershell window,  you need to run visual studio from that window as well. This is so that visual studio uses the same version of the SDK that you're using on the command line.
