### ISSUE TITLE
Multiple authentication schema

### ISSUE THREAD

**Issue by adrianMustelier** [aspnet/Security#1381]
I have a problem configuring multiple authentication schemas. the code is as follow

```C#
services.AddAuthentication()
            .AddJwtBearer(JwtBearerOptions =>
            {
                JwtBearerOptions.TokenValidationParameters = tokenValidationParameters;
            })
            .AddFacebook(facebookOptions =>
            {
                facebookOptions.AppId = "xxxxxxxxxx";
                facebookOptions.AppSecret = "xxxxxxxxx";
                facebookOptions.SaveTokens = true;
                facebookOptions.AuthorizationEndpoint = FacebookCurrentDefaults.AuthorizationEndpoint;
                facebookOptions.TokenEndpoint = FacebookCurrentDefaults.TokenEndpoint;
                facebookOptions.UserInformationEndpoint = 
 FacebookCurrentDefaults.UserInformationEndpoint;
                facebookOptions.Scope.Add("email");
                facebookOptions.Fields.Add("name");
                facebookOptions.Fields.Add("email");
            });
```

with this configuration if I try to authenticate using JWT, authentication fail and  "Identity.Application Schema" it is used by default. The authentication using FB success. If I want to use JWT, I have to use the following code. 

```C#
 services.AddAuthentication(options =>
            {
                options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
            })
```
but with this configuration FB Authentication fail. It seems like I only can use one Authentication Schema 

from my understanding. Method AddScheme from AuthenticationSchemeProvider only allow handlers that implement IAuthenticationRequestHandler. So JWTBearer Handle is exclude from _requestHandlers

```C#
 if (typeof(IAuthenticationRequestHandler).IsAssignableFrom(scheme.HandlerType))
 {
       _requestHandlers.Add(scheme);
  }
```

Also Method Invoke from AuthenticationMiddleware cast the returned handler that result in a a null handle for those handle that doesn't  implement IAuthenticationRequestHandler, in this case for JwtBearerHandler. So if JwtBearerHandler is not set as Default, never could  handle the request.

```C#
 foreach (var scheme in await Schemes.GetRequestHandlerSchemesAsync())
 {
       var handler = await handlers.GetHandlerAsync(context, scheme.Name) as 
                             IAuthenticationRequestHandler;
       if (handler != null && await handler.HandleRequestAsync())
       {
              return;
        }
 }
```

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Security/issues/1338 and https://github.com/aspnet/Security/issues/1310.

You're not showing your whole config. The error implies you have AddIdentity as well, which is causing conflicts.

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.

**Comment by vgribok** [comment]
I have same issue with two custom/non-standard auth schemes: requests with an `Authorize` header work only if default auth schema is specified, effectively making only one, default, schema working.

It happens because on [this line](https://github.com/aspnet/Security/blob/df325deaf355f99239c1319932bc28eb3a837372/src/Microsoft.AspNetCore.Authentication/AuthenticationMiddleware.cs#L42) `Schemes.GetRequestHandlerSchemesAsync()` call returns empty collection. It is empty because `AuthenticationSchemeProvider._requestHandlers` collection is empty, even though `AuthenticationSchemeProvider._options.Schemes`, which serves as a source for building `_requestHandlers`, is populated as expected. That happens, evidently, because logic of converting `_options.Schemes` into `_requestHandlers` is too eager, being placed into the  [AuthenticationSchemeProvider(IOptions<AuthenticationOptions> options)](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationSchemeProvider.cs#L21) constructor.

Suggested fix is to make `_requestHandlers` initialization more lazy.
