### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mirshahreza** [aspnet/Security#1392]
I am using vs 2017 15.3. I get this repo and try to compile the solution. but there are some bugs:

for example :
1-public class InitializeAuthenticationSchemeOptions<TOptions> : InitializeOptions<TOptions>
2-return AuthenticateResult.None();

and so on.

Visual studio message shows there are some missing assembly.

**Comment by jkotalik** [comment]
For the first one, make sure you have the assembly `Microsoft.Extensions.Options`.  InitializeOptions is also generic, so you will need to consider that too. The second one requires `Microsoft.AspNetCore.Authentication`. Also, I  believe AuthenticateResult.None is a property on Authenticate Result, meaning you need an object in order to reference it. Try AuthenticateResult.NoResult() if you are calling it statically.

**Comment by Tratcher** [comment]
We recommend you compile from the command line first (build.cmd), it pulls the right versions of all the dependencies. VS has a hard time keeping up with dev.

**Comment by mirshahreza** [comment]
I check the references. projects have the right references !!! 
I download the full solution from this repo ant I think it must be compilable !!!

**Comment by Eilon** [comment]
@mirshahreza can you run `build` from the command line? Also make sure all your NuGet caches are cleared.

**Comment by mirshahreza** [comment]
I test the command line and the problem exist yet. but when I downloaded the newest version I saw new problems : sample projects failed for load in the solution !!! and the rest of issues are exist yet.

**Comment by Eilon** [comment]
Can you show the exact output of the build? Maybe upload the whole output file to GitHub?

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.
