### ISSUE TITLE
Mixed Authentication

### ISSUE THREAD

**Issue by shishir28** [aspnet/Security#1417]
Hi 
I am trying to create a web application on asp.net core 2.0  where business requires me to support active directory as well and form based authentication . 
For people within the organization I should  avoid the logon process and for people from outside , it should show the logon screen. 
I could not find any leads so only possibility I can think of using Microsoft.AspNetCore.Hosting.ini file and have two separate deployments one uses windows authentication and other form based.   
Can anyone suggest me better way of achieving it?  

Thanks

**Comment by Eilon** [comment]
@blowdart can you take a look at this and offer some suggestions?

cc @vibronet because he also has some thoughts on this.

**Comment by blowdart** [comment]
There is nothing built in and generally we tell people to avoid this like the plague because it's very hard to do securely, because you end up with a single system supporting what is probably different levels of trust depending on the user source, and no real way to tell if a login came from AD, or from random forms.

Two separate deployments is safest. You could also, maybe, if your AD is up to it, look at ADFS 2016, and have your external users with accounts inside your AD. That might make your network people unhappy, but it'd do what you want, and then, because all the identity comes from a single source, you don't have to worry about duplicates, and you can use AD groups/roles to manage privilege levels.

**Comment by brockallen** [comment]
Or you can design around the use of OpenID Connect and use IdentityServer to be your authentication service. IdentityServer can then do this brokering for mixed authentication you're asking for. In fact, we show that in this video: https://mva.microsoft.com/en-US/training-courses/introduction-to-identityserver-for-aspnet-core-17945

**Comment by shishir28** [comment]
@blowdart Sorry for responding late and Thanks for your prompt response. We have decided to go ahead with separate deployment as of now .   Once I again my apologies for not responding on time . 

Thanks 
Shishir
