### ISSUE TITLE
OpenIdConnect flow does not set the SignInAsAuthenticationType cookie

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Security#144]
Checkin : https://github.com/aspnet/Security/commit/3483842ab76d4198fc230c7a1905b0ada9b4bf89#commitcomment-9535319 seems to break openIdconnect flow as it does not set the external cookie. 

Test failure here : https://github.com/aspnet/MusicStore/commit/7783c368569fbaf267121eff8eedefbd05cb974d is due to this.

**Comment by PinpointTownes** [comment]
On a side note, `OpenIdConnectAuthenticationMiddleware` doesn't use a correct value for `TokenValidationParameters.AuthenticationType`: it should use `Options.AuthenticationType` instead of `externalOptions.Options.SignInAsAuthenticationType` to make sure that the `ClaimsIdentity` returned by `AuthenticateCoreAsync` has the same `AuthenticationType` as the middleware itself.

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Security.OpenIdConnect/OpenIdConnectAuthenticationMiddleware.cs#L51

**Comment by Praburaj** [comment]
@brentschmaltz
