### ISSUE TITLE
UseOAuthAuthentication ignores configureOptions parameter

### ISSUE THREAD

**Issue by vncastanheira** [aspnet/Security#153]
Current implementation ignores your `Action<OAuthAuthenticationOptions<IOAuthAuthenticationNotifications>>` parameter. For example, if you call  `UseOAuthAuthentication`, like in:
```
app.UseOAuthAuthentication(OAuthBearerAuthenticationDefaults.AuthenticationType, o => new OAuthAuthenticationOptions<IOAuthAuthenticationNotifications>
{
  ClientId = "0000000"
});
```
it will raise an exception saying that `ClientId` was not defined. These lines
```
if (configureOptions != null)
    configureOptions(options);
```
could be changed to 
```
if (configureOptions == null)
    configureOptions(options);
```
so it won't replace the user-defined `configureOptions` variable.

**Comment by PinpointTownes** [comment]
:scream_cat: 

Your first snippet doesn't correspond to the way the extension method should be used (see https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L45-L55 for a sample) : you simply create a new options instance instead of updating the existing one (represented by your `o` parameter), and that's why you get an exception for the mandatory `ClientId` parameter.

(BTW, the suggested fix is terrible and will necessarily trigger a NRE exception :laughing:)

**Comment by vncastanheira** [comment]
Well, this is confusing. I thought it would create an OAuth service provider. :disappointed: 
But that clarified a bit.
