### ISSUE TITLE
Question: Register/Configure OpenIdMiddleware at runtime

### ISSUE THREAD

**Issue by Jenan** [aspnet/Security#1533]
Hello,

is it possible register/configure the OpenIdMIddleware at runtime from application? I am wondering about register new external provider like facebook or twitter from application? If is it necesarry change some parameters in the middleware and is it required go to the code and re-deploy/restart app?

Thank you.

**Comment by Eilon** [comment]
@HaoK can you provide a sample of how to do this?

**Comment by HaoK** [comment]
You can do this but it is a bit involved:

Basically you will need to implement a custom `IOptionsMonitor<OpenIdConnectOptions>` which is able to resolve the named options dynamically since the built in implementation requires things to be configured in `ConfigureServices`.  

There's not much to implement, you basically will just need to implement `Get(string name)` to return the appropriately configured options, you could implement one for each type of auth, i.e. `IOptionsMonitor<FacebookOptions>`, `IOptionsMonitor<GoogleOptions>`

You can add a handler dynamically at runtime via the `IAuthenticatinoSchemeProvider.AddScheme` method:

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Authentication.Abstractions/IAuthenticationSchemeProvider.cs#L72

You can see a test that demonstrates adding schemes here: https://github.com/aspnet/Security/blob/dev/test/Microsoft.AspNetCore.Authentication.Test/DynamicSchemeTests.cs#L142 

You will need to just add `services.AddSingleton<IOptionsMonitor<FacebookOptions>, CustomFacebookMonitor>` for each of the options you want to configure dynamically.

Let me know if you need more clarification on any of these areas

**Comment by Tratcher** [comment]
Move to AuthSamples for a new sample?

**Comment by HaoK** [comment]
Sure https://github.com/aspnet/AuthSamples/issues/3
