### ISSUE TITLE
AuthorizationPolicy should allow a custom failure message and failure status code

### ISSUE THREAD

**Issue by choudeshell** [aspnet/Security#1560]
In ```Microsoft.AspNetCore.Authorization, Version=2.0.0.0```,  a non-successful ```AuthorizationPolicy``` always returns a 403-Forbidden status code with an empty response body/empty result.

It would be useful to have ```AuthorizationHandlerContext``` expose a ```AuthorizationRequirementResult``` that is passed through the pipeline so that the resulting response allows a custom message and status code. 

Along with ```AuthorizationRequirementResult``` being added, an 'immediate fail' flag should be added to ```AuthorizationHandlerContext``` so that no other handlers would be called. This would guarantee that the handler setting the ```AuthorizationRequirementResult``` would be used. If 'immmediate fail' is not triggered,  subsequent handlers would have the opportunity to reset/overrwite the ```AuthorizationRequirementResult```.

A sub-optimal workaround  at the moment, is to set the result within the ```AuthorizationHandlerContext``` and set the status of 'success' to a failed policy. This allows the default Result behavior to be triggered -- ultimately returning a custom message and status code. 

```c#
public class ActiveUserAuthorizationHandler : AuthorizationHandler<ActiveUserRequirement>
{
    protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, ActiveUserRequirement requirement)
    {
        var authorizationFilterContext = context.Resource as AuthorizationFilterContext;
        var userAccessor = authorizationFilterContext.HttpContext.RequestServices.GetService<IUserAccessor>();

        if (userAccessor.User.IsActive)
        {
            context.Succeed(requirement);
        }
        else
        {
            authorizationFilterContext.Result = new JsonResult("Need a custom message") { StatusCode = 418 };
            context.Succeed(requirement);
        }

        return Task.CompletedTask;
    }
}
```

**Comment by Eilon** [comment]
There are two separate concerns here:
1. Deciding what to do when a policy/auth rule fails
2. Implementing some code that is framework-specific that handles that result

Mixing both of those into the Auth Handler is somewhat problematic because it assumes that the result will be processed by MVC (i.e. `AuthorizationFilterContext`)

We agree there isn't currently a great built-in story for this but it would probably look something like:

1. Have the AuthHandler be focused only on making a decision about how to interpret a failure
2. Have framework-specific code (such as an MVC auth filter, or some new extensibility within MVC's existing auth filter) interpret that result and convert it to an HTTP response

**Comment by HaoK** [comment]
This is a probably a dupe of https://github.com/aspnet/Security/issues/1530 which is tracked as part of https://github.com/aspnet/Security/issues/1359 (AuthZ improvements for 2.1)

**Comment by Eilon** [comment]
Ah, you're right, we thought there was a dup somewhere.

**Comment by davormas** [comment]
This one might be duplicate but it gave me dirty hack workaround that is just enough for my case. Thanks!
