### ISSUE TITLE
Empty policy support

### ISSUE THREAD

**Issue by Swazimodo** [aspnet/Security#1596]
I am trying to build a .NET Core application which uses .NET Framework references. Currently if you set up your application policies in a way that allows them to be configurable, it will cause runtime errors if you want to remove all access from one of them. 

On the controller you would have a hard coded policy name that is needed for access
`[Authorize(Policy = "View")]`

Then in the startup.cs file you would have some logic to dynamically create those policies with configurable AD groups. However with this approach the application will not create a policy if the AD group value is null or empty. I also tried using values like 'Nobody' but that didn't work either. If the policy is not created, then when a controller is called it does not actually have an application policy with that name and an exception is thrown.

        //set the active directory access group
        services.AddAuthorization(options =>
        {
            ApplicationRoles roles = Configuration.GetSection("Roles").Get<ApplicationRoles>();
            foreach (var role in roles.GetApplicationRoles())
            {
                options.AddPolicy(role.RoleName, policy =>
                {
                    policy.RequireAuthenticatedUser();
                    policy.RequireRole(role.ADGroups);
                });
            }
        });

Especially for testing purposes it would be really nice to be able to deny all to a policy.

**Comment by blowdart** [comment]
Why not check the configured database rules inside the policy handler, rather than create a policy from scratch at runtime?

**Comment by HaoK** [comment]
You can still have a deny all for testing purposes, just by having a Policy with a single requirement with no handlers.

**Comment by Swazimodo** [comment]
@blowdart that may have been a better approach but I still think it should have allowed a policy to be created without any access. I think this would be a bug.

**Comment by Swazimodo** [comment]
@HaoK Could you elaborate? When I have tried to remove the groups from a policy it is not created which causes run-time exceptions instead of a 401 or 403 response.

**Comment by blowdart** [comment]
@Swazimodo I disagree it's a bug, A missing handler is a serious thing, it indicates a pretty bad problem, which is why we error. Otherwise a simple spelling mistake could mean unauthorized access.

**Comment by HaoK** [comment]
Just to clarify, its by design that we don't allow empty policies because that's always an error since it will never succeed, you might as well just return false for that policy.  So a policy must have at least one requirement.  But there's nothing that requires any handlers being added to the system, which by default means no authorization requirements will ever succeed.

**Comment by HaoK** [comment]
@Swazimodo I think your confusion is the difference between requirements (stuff like RequireRole/Claim) is sugar for adding requirements.  And auth handlers (which are things that handle requirements), the sugar hides this distinction as those requirements typically handle themselves.

**Comment by Swazimodo** [comment]
Is there any examples you can point me to then which would allow you to define AD groups for application roles? It would have to be possible to remove all groups and have that remove all access without breaking the application.

**Comment by blowdart** [comment]
That's kinda specific for an example, especially as it'd rely on having an AD present, which most people don't. I could knock up something which uses a mock service and a Dictionary during the week.

What I would do is, in your [custom policy](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies) you'd take the policy name and go off to your database and say "Hey give me the AD roles that currently fulfill this policy name", then check the current user's membership. You'd probably want to cache the list for a while, otherwise it's going make requests expensive. If there are no groups coming back from your query then you'd just not call .Succeed() 

What this does require is you to predefine your policy names, which makes sense, because it's not like you add policies to controllers at runtime with any degree of ease.

**Comment by Swazimodo** [comment]
Thanks for your comments here. I'll see what I can do to make this work.
