### ISSUE TITLE
Username contains leading "live.com#" prefix after signing in with AzureAD

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Security#1717]
After creating a project using Visual Studio, using org auth (AzureAD), and running it, the username displayed includes an unexpected prefix, in this case "live.com#".

**Expected**
Username is displayed as *damian@damianedwards.com*

**Actual**
Username is displayed as *live.com#damian@damianedwards.com*

Screenshot:
![image](https://user-images.githubusercontent.com/249088/38340947-f9f4c748-382a-11e8-863f-f75b647a4116.png)

**Comment by brockallen** [comment]
When you login via AAD with a live account, they issue two name claims. One of them is what you see above. The other is a First/Last combo, which is the one you're expecting.

**Comment by brockallen** [comment]
One is the "name" claim type (the one you want), and the other is the ws-* claim types (the one you seem to use now and are using the ClaimTypes constants).

**Comment by blowdart** [comment]
Having a LiveID in an AAD is legacy, that's why you get that annoying message when you login. The vast majority of AAD tenants are not going to be in this situation, because they cannot have LiveIDs inside them, that functionality was blocked years back, it's just folks like you and I that see this.

So won't fix, can't fix, don't use your Live ID, use your AAD account.
