### ISSUE TITLE
Use JWT token cookie in combination with Authorize attribute

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/Security#1770]
I have two web applications, one API and one MVC application. From the web application I request a JWT token from the API using Javascript and store the response in a cookie. Then in the MVC application I would like to setup authorization using the JWT token from the cookie I recieved from the API. What is the best approach if I want to add security on a `Controller` using the `Authorize` attribute and how would I configure this in the MVC application?

**Comment by blowdart** [comment]
There is JWT middleware, but it's assuming you're using the JWT as a bearer token, sent in headers.  However you could use the OnMessageReceived event available in options to pick the JWT token from the cookie, rather than the header, that exposes a MessageReceivedContext which has a token property.

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
