### ISSUE TITLE
OpenIdConnect nonce cookies - overflow handling

### ISSUE THREAD

**Issue by loctanvo** [aspnet/Security#179]
This issue was originally posted on CodePlex in the Katana issue tracker. Since the OIDC middleware has been moved to this project, I'm now opening an issue here instead. 

Please read the conversation there before adding comments here.

http://katanaproject.codeplex.com/workitem/402

**Comment by muratg** [comment]
@brentschmaltz @Tratcher @Praburaj

**Comment by jmickael** [comment]
this problem started for me when I upgraded to OWIN 3.0.1   The only way I can clear the error is to restart my Azure website.( NOT an option in production).  Has anyone found a workaround or is there an ETA on a patch for this problem?

**Comment by loctanvo** [comment]
@jmickael We have just temporarily downgraded the OpenID Connect Middleware to 3.0.0, and the problem disappears. You can still use OWIN 3.0.1 though, just keep the OIDC one on 3.0.0. Just curious; how can you solve the problem by restarting the Azure website? The cookies are kept in the client. Just clear those, and you should be fine.

The actual fix should not be too difficult (have not looked into the code yet though). @brentschmaltz @Tratcher @Praburaj , do you accept PR from others? If time allows, I may have a look at it (but no promises). I recently contributed to [IdentityServer3](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/Hosting/MessageCookie.cs#L218) with somewhat similar functionalities. I still have it relatively clear in mind how they do overflow handling.

**Comment by brentschmaltz** [comment]
@loctanvo if you have filled out the 'paper work' we are happy to take PR's. In fact we encourage it.
I agree this is an issue. 

The fix is a bit trickery than it seems, there are some corner cases.

**Comment by loctanvo** [comment]
@brentschmaltz Sorry for not giving any update on this. I've been very busy lately, and have not had time to look into this. If time allows (looking bad the next weeks, though), I will give it a go. I'll definitely give you a heads up before I start looking into it. In other words, don't wait for me if you have capacity to look into this issue in the near future.

**Comment by AdamDotNet** [comment]
Hi, I came here from the issue @loctanvo referenced. I am not sure how to do a formal pull request, but for now, my app's solution is to extend the middleware so I can setup an extended OpenIdConnectAuthenticationHandler.

My ultimate solution was to delete all nonce cookies that weren't the current one upon calling RememberNonce.

Here's the handler code:

```C#
public class SawtoothOpenIdConnectAuthenticationHandler : OpenIdConnectAuthenticationHandler
{
	public SawtoothOpenIdConnectAuthenticationHandler(ILogger logger)
		: base(logger) { }

	protected override void RememberNonce(OpenIdConnectMessage message, string nonce)
	{
		var oldNonces = Request.Cookies.Where(kvp => kvp.Key.StartsWith(OpenIdConnectAuthenticationDefaults.CookiePrefix + "nonce"));
		if (oldNonces.Any())
		{
			CookieOptions cookieOptions = new CookieOptions
			{
				HttpOnly = true,
				Secure = Request.IsSecure
			};
			foreach (KeyValuePair<string, string> oldNonce in oldNonces)
			{
				Response.Cookies.Delete(oldNonce.Key, cookieOptions);
			}
		}
		base.RememberNonce(message, nonce);
	}
}
```
Note that `OpenIdConnectAuthenticationDefaults.Nonce` is an internal constant or I would have used that in my linq query.

If this is somehow terrible, or insecure, please let me know.

**Comment by brentschmaltz** [comment]
I can't think of a reason that we shouldn't clean up all the cookies after validation. Not sure about deleting them before the user is validated.

**Comment by brockallen** [comment]
The only possible concern is multiple tabs -- not sure if that's a scenario you guys want to allow/support.

**Comment by AdamDotNet** [comment]
@brockallen makes a valid point about potentially deleting cookies from other tabs. I thought of deleting the extra nonces before sign in because in my app, it is an eventual possibility that users could generate so many nonces so as to get a Request Too Long error, all before actually signing in.

I just tried multi tabs on my solution and Identity Server returns the message:
"There is an error determining which application you are signing into. Return to the application and try again." Understandable why it happened. I guess the question is, how bad is that compared to being cookie locked out of a website or entire series of websites because the single sign on is spread out to many sites?

**Comment by brentschmaltz** [comment]
Multiple tabs may mean different apps using the same IdentityProvider. In this case some IDP's cache a sesson with the browser. User is not required to re-auth at the IDP but receives a fresh token.

@AdamDotNet what IdentityServer were you using?

**Comment by AdamDotNet** [comment]
@brentschmaltz I'm using https://github.com/IdentityServer/IdentityServer3

The message quoted was more related to the SignInMessage cookie missing than the nonce though, now that I think about it more.

**Comment by erikbra** [comment]
I might be daft, but, what is really the use-case for the issue mentioned in https://katanaproject.codeplex.com/workitem/344 ? You want to login to the same application with two different users in the same browser? How on earth can the web application separate the two sessions server-side once you're finally logged in? Or do I misunderstand the use-case?

Another concern is the use of "session" cookies. Say we find a strategy to delete the nonce cookies after the authentication is OK, as @brentschmaltz mentions. What if, for some reason, the cookie is not deleted (the user aborts the authentication, or, whatever). Then, the next time  the user tries to log in, a new nonce cookie is generated. The problem with modern browsers (e.g. Chrome), is that session cookies are effectively kept forever, since people never actually quit their browsers. The cookies might also be sync'ed between browsers if the user logs into her browser. How about setting a timeout of, say, 5 mins, instead?

**Comment by jmickael** [comment]
Erik,

Thanks for the feedback.

 

The problem I am experiencing is when users are accessing my application after they log out or in some cases use a different Microsoft account.  Our organization uses Office 365 E3 and all our users will “signon” to office 365 using the web clients.  We developed a custom application that uses the same Office 365 AD Tenant to authenticate users.  When the user firsts authenticates to Office365 to use outlook the nonce cookie is cached.  I think it might be due to the TokenCache inside the application retaining prior user identity.  

 

I’m going to open a support ticket with MS to see if there is an update to this issue.  I haven’t looked at this for a few months due to work load…

**Comment by erikbra** [comment]
I'm starting to think this is a bigger issue. I've tried to solve this looking at the Katana source code, I've tried to google it, and it seems many people have this issue, with very different applications, not all using Microsoft.Security.OpenIdConnect (not that I know, at least).

### Examples (found by googling IDX10301):

BizTalk service portal SSO: https://social.msdn.microsoft.com/Forums/sqlserver/en-US/55e45519-f00b-427c-882b-96e28b9518f4/bug-biztalk-service-portal-sso-crash-upon-relogin?forum=azurebiztalksvcs

ADAL (this is "us"): http://stackoverflow.com/questions/26677772/adal-in-a-loop-on-the-webserver

IdentityServer (by @leastprivilege): https://github.com/IdentityServer/IdentityServer3.AspNetIdentity/issues/18

And in our own application, using Azure AD and OpenID connect.

The error is present in both  3.0.0 and 3.0.1, but are a bit different. In 3.0.0, you just loop between the RP and the IDP. In 3.0.1, you loop, but get more and more nonce cookies, each with different names (which was supposed to solve the issue)

If you look at the error messages, something peculiar comes to mind:

```
IDX10301: The 'nonce' found in the jwt token did not match the expected nonce.
expected: '635592349230300438.YTc4MDI0NmYtZDAzMy00YWU0LTg1MWItNmM5YjFlM2Q3YWZlNGI3MzdlMjgtMjk2Ni00NTQ3LWJhNzYtMjM4MzQxMmRkNWMy'
found in jwt: '635592349850407122.ZWQzMWZhMmYtNDA4Zi00YmFmLTkzZWItMWNjZjIxN2ZkYzcwZGE5YTYwMGEtMzc0MC00NmU4LWE2MmYtYTM3NTczMTQ5OWIz'.
jwt: '{"typ":"JWT","alg":"RS256","x5t":"MnC_VZcATfM5pOYiJHMba9goEKY"}.{"aud":"4b1feced-a36d-4e0a-ad97-d66319026ce6","iss":"https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/","iat":1423637906,"nbf":1423637906,"exp":1423641806,"ver":"1.0","tid":"f8cdef31-a31e-4b4a-93e4-5f571e91255a","amr":["pwd"],"email":"some@live.com","idp":"live.com","altsecid":"1:live.com:0003BFFD9C87345C","sub":"iPCzTHkaDYVLQFhpTjUy-94WITrv-1z4KfvHxe1JOws","given_name":"some","family_name":"some","unique_name":"live.com#some@live.com","nonce":"635592349230300438.YTc4MDI0NmYtZDAzMy00YWU0LTg1MWItNmM5YjFlM2Q3YWZlNGI3MzdlMjgtMjk2Ni00NTQ3LWJhNzYtMjM4MzQxMmRkNWMy","c_hash":"Zp47H1us_GhXgYtxufYbLA"}
```

Look at the `expected` and the printout in the `jwt` JSON. The nonces are the same. But, in `expected`, another value appears. It seems as if the `expected` value is the incorrect one.
I have tried finding out which component generates IDX10301 in the first place, but it doesn't look to be `Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationHandler` itself. Can't find IDX10301 anywhere in the Katana solution.

Are we sure we are fixing the right problem?

**Comment by Eilon** [comment]
We think the case of solving extra cookies isn't super important because it's a symptom of a larger problem of a mis-configured auth system. The cookies will expire after an hour anyway and be cleared out. We are concerned that any attempt to clean up bad cookies from the server is too dangerous because of the multiple-browser-tabs scenario.

**Comment by brockallen** [comment]
_the case of solving extra cookies isn't super important because it's a symptom of a larger problem of a mis-configured auth system_

Disagree. People open tabs. There's nothing you can do to configure how people use their browsers.

**Comment by Eilon** [comment]
@brockallen perhaps we missed something when we reviewed this issue. It's not that we don't want to support multiple-tabs - that's a super common scenario, obviously.

Our conclusion was this:
* With a *properly* configured auth system, the cookie will get set, and then later consumed, and go away when the authentication completes, because there are no errors.
* With an *improperly* configured auth system, you can't login at all (duh), so what happens to the cookies doesn't matter at all. You might end up with tons of bad cookies for all the failed login transaction attempts. In this scenario the cookies will eventually expire after the 1-hour default expiration time.

Is there another case here that we've missed?

**Comment by brockallen** [comment]
I just want to ensure that a person opening 2 tabs will be able to login to both. If one tab sets one nonce cookie and the other sets a different value in the same named cookie then one will no longer work because it was overwritten. This is ideal for both end-app, as well as frameworks (such as IdentityServer) that's built with the cookie middleware.

**Comment by Tratcher** [comment]
That's what the feature we did in Katana 3.0.1 was for. Nonce's now have a unique identifier in their name, so two browser tabs can log in independently of one another. One possible side-effect is that if the user never completes the login flow in one of those tabs, you'll be left with that stale nonce cookie for an hour until it expires. There's no way for us to know if the user has closed that other tab or not, so we can't preemptively clean up that cookie for them.

This is all considered non-impactfull since browsers will discard old cookies if they have too many, or when they expire.

**Comment by brockallen** [comment]
Ok, so just so I'm clear -- the Katana 3.0.1 behavior was rolling into ASP.NET 5's cookie MW? If so, then I'm happy.

**Comment by Tratcher** [comment]
The nonce cookie was never set via cookie middleware, OIDC sets it directly. The Katana OIDC 3.0.1 behavior was rolled forward into K's OIDC 1.0.0-beta*.

**Comment by brockallen** [comment]
Excellent -- then that's all I was trying to ensure. Apologies for misunderstanding the above comments then. Thanks.

**Comment by jmickael** [comment]
Brock,

Thanks for all your effort on this nonce cookie issue.  It looks like issue https://github.com/aspnet/Security/issues/179 is closed.  When do you think the release might happen with this change?

 

Thanks again

**Comment by brockallen** [comment]
This is Microsoft's repo, not mine. So I don't know the answer.

**Comment by Eilon** [comment]
@jmickael what change are you referring to?

**Comment by jmickael** [comment]
I've seen a couple posts including this one where a recommendation to clean up nonce cookies was made.  I had issues upgrading the Microsoft.Owin.Security.OpenIdConnect to version 3.0.1.  I was told to roll back to 3.0.0 to stop getting the "header too big" exception.  I was wondering if version 3.0.1 has cookie cleanup added and put on NuGet yet?

            foreach (KeyValuePair<string, string> oldNonce in oldNonces)
            {
                Response.Cookies.Delete(oldNonce.Key, cookieOptions);
            }

**Comment by Eilon** [comment]
@Tratcher can you help answer this?

**Comment by Tratcher** [comment]
No, there's no verbose cookie cleanup in either Katana or Asp.Net 5. OIDC only deletes the cookie for the redeemed nonce, not for any of the unredeemed ones. We don't know if the others will eventually be redeemed (e.g. in another tab). If you want to keep discussing Katana please go back to http://katanaproject.codeplex.com/

**Comment by vladimirlapacek** [comment]
@Eilon you mention that the cookies expire in an hour and get cleared, but I am not convinced that it is the case. The current source code suggests that the cookies are only cleared when you close the browser. The expiration seems to be only taken into account when validating the Nonce in OpenIdConnectProtocolValidator. That means that the cookies can stack up over long period of time in case the browser process does not exit, which is quite common with Chrome. Am I missing something? Can the cookies expire based on age as well? Or maybe can we introduce an optional count limit as was originally suggested in http://katanaproject.codeplex.com/workitem/402 by @loctanvo ? I think it is still better to kill one of x cookies than showing the user a page with error 400.

**Comment by Tratcher** [comment]
@vladimirlapacek Ah, you're right, the cookie itself does not expire. https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationHandler.cs#L589-L596
All told I think using Options.NonceCache is a better solution than using cookies.

**Comment by Eilon** [comment]
@Tratcher should we add any additional expiration logic then?

**Comment by Tratcher** [comment]
I don't think it would help, users are most likely hit this in the first few minutes (redirect loop) so an expiration wouldn't have time to remove old cookies.

Can we remove cookie support and require server side nonce caching?

**Comment by Eilon** [comment]
@Tratcher can you log an issue specifically on that and we can discuss in the next mtg?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/issues/390

**Comment by vladimirlapacek** [comment]
@Eilon, @Tratcher thanks for the quick response and considering the options. Let me just add that the problem can surface after a longer time if the user does not finish the login here and there for whatever reason. It does not necessarily need to be a quick loop due to misconfigured server.

The CacheNonces sounds promising. I suppose that there won't be a 3.x.y version of the OIDC middleware adding such feature, though.

**Comment by Tratcher** [comment]
How many incomplete logins do you need before you start getting 400s? I expect it to be many.

Correct, the nonce cache is not in v3.

**Comment by loctanvo** [comment]
@Tratcher Since the nonce cookie is set on the client application's domain, it really depends on which other cookies already exist on that domain. When the sum of the cookie sizes are large enough, it will exceed the header limit (regardless of a redirect loop/misconfiguration or not). Just as a comment on your previous comment.

**Comment by vladimirlapacek** [comment]
@Tratcher I just discovered 2 interesting aspects of the Chrome browser (which now has the biggest market share). By default it does not clear the session cookies upon closing window (Continue where you left off) and I have also noticed that it sometimes duplicates requests, which may yield two nonces instead of just one. Only one gets deleted upon completing the login. The point is that reaching error 400 may be easier than it seems.

**Comment by loctanvo** [comment]
@vladimirlapacek I can confirm your findings regarding session cookies. Chrome does not clear session cookies before you have exited all chrome processes. So, if you have something running in the background, eg. Hangout, you'll keep the session cookies for quite some time.

Regarding chrome duplicating requests: I've noticed that when typing in a url, chrome will automatically make the request before the user hits Enter. I guess it's for preloading and make the user experience appear faster.

**Comment by vladimirlapacek** [comment]
@loctanvo let me go even further. Chrome does not recycle the cookies even if you terminate the process. The *Continue where you left off* setting makes them essentially persistent. That really confused me.

As for the cookie duplication, I am experiencing random request duplication hitting my server at the very same time. Not sure how that works internally, but it seems to stop if I turn off the *Prefetch resources to load pages more quickly*.

Both settings are enabled by default...

**Comment by whoever123** [comment]
Is there a solution to this yet?  The issue was closed but I can't find any

**Comment by Tratcher** [comment]
We added a 15 minute timeout to the nonce cookie to help mitigate the issue.

**Comment by whoever123** [comment]
Thank you so much for the follow up.  Is there any particular version, step or configuration I need for this to apply?  I run into this issue a few month ago when going through IdentityServer3 MVC walkthrough sample.  I think already have all the latest nuget packages this time around by starting from scratch.  

Nothing too complicated, just one Identity Server and two sample MVC apps sitting on 3 servers.  Now two hours later, I try to logon to one of the app, still got bad request.

**Comment by Tratcher** [comment]
You need beta8-15599 or later, from Sep 9th. You'll also want to clear your old cookies because the fix isn't retroactive.

**Comment by whoever123** [comment]
Upon further inspection, there's a chance that my nounes were piled up through a constant redirect during logon.  Here's a link describing the issue of conflict between .NET and OWIN session.

http://stackoverflow.com/questions/20737578/asp-net-sessionid-owin-cookies-do-not-send-to-browser/21234614#21234614

I'm not 100% sure yet but it's very likely, since one of my test app is "hello mvc" and the other is converted from an existing app with plenty of regular session use.

Have you heard of this?  Is there an more official solution to this than hack-it-away?  Thanks.

**Comment by Tratcher** [comment]
See here: http://katanaproject.codeplex.com/wikipage?title=System.Web%20response%20cookie%20integration%20issues&referringTitle=Documentation
However, that only applies to Katana. ASP.NET 5 isn't affected by that session issue.

**Comment by whoever123** [comment]
I have been waiting for that next big thing since PC DOS 1.1 ^_^

One of the hack is just to add a dummy session variable on Session_Start.  Seems a lot less work to go around.  Do you see any potential issue with that approach?

**Comment by Tratcher** [comment]
Should be fine so long as that doesn't happen on the same request where any Katana cookies are issued.

**Comment by whoever123** [comment]
Really appreciate the help.

**Comment by RonniePitts** [comment]
Hi Guys,
I've just experienced the HTTP 400 - Bad request issue around the various nonce cookies. First time I've seen this since moving to 3.0.0.1 Open ConnectID.
Is this now fixed?   
Yes I'm using chrome. 
I've seen some looping issues (login.microsoftonline.com) as well which  probably doesnt help.

**Comment by Tratcher** [comment]
@RonniePitts You need beta8-15599 or later, from Sep 9th.

**Comment by RonniePitts** [comment]
OK Thanks @Tratcher. 
I'm assuming this is rolled into ASP.NET 5 dev branch at the moment? 

Not a simple nuget package update :-)

**Comment by Tratcher** [comment]
Yes, its in dev and should be out on https://www.myget.org/F/aspnetwebstacknightly/

**Comment by thomius** [comment]
What workaround and how to apply when using .NET 4.6 (or .NET 4.5)?

@loctanvo mentioned on March 16 that downgrading to 3.0.0 fixed the issue - but does this only mean the nonce cookies? @erikbra commented on June 3 that also 3.0.0 would suffer from the redirect loops.

**Comment by loctanvo** [comment]
@thomius: there are two (if not more) problems described in this issue discussion:

1. Nonce cookies are not cleared properly if the authentication requests are not completed, resulting a `Request too long` problem.
2. Eternal redirect loop due to cookie not being found.

My suggestion to downgrade to 3.0.0 will only fix the first problem, while problem 2 is somewhat unrelated.

**Comment by thomius** [comment]
@loctanvo ok. In our MVC application the nonce errors were caused by the redirect loop (as probably with many others)

1. TempData is used somewhere in the application (TempData["Your changes were saved!"])
2. Current user thinks everything went fine / doesn't see any problems...
3. ... but now every other user who tries to sign on gets into an eternal redirect loop! OWIN 3.0.1 generates a nonce cookie each time leading to the IDX10301 nonce exceptions. The issue stays on until the application is reset/recycled except for users who got into Request Too Long due to nonce cookies

We fixed the issue by adding the SystemWebCookieManager mentioned here in this article: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationHandler.cs#L589-L596

Also we had downgraded to OWIN 3.0.0 earlier to get rid of the nonce cookie exceptions but i'm not sure if 3.0.0 had issues why it would be better to upgrade to 3.0.1 despite the nonce cookie error

**Comment by liquidboy** [comment]
sorry to bring up an old issue BUT I just encountered this today with our ASP.NET MVC app using OpenIDConnect ...  in this issue #770    

Basically our testers were routinely getting the "bad request" problem as their automated tests are doing MANY redirects per second and thus hitting browser max cookies with nonce cookies..  (as per attached images in my issue)

**Comment by venkatrv** [comment]
Yes, I am also getting bad request error because cookie is too long and keep appending to request.
I saw so many users mentioned this issue in the net, but could not find a solution.
Is there a solution for this? or should I dropout identityServer3 because of this issue? if so, any other products can give similar functionality without the nonce issue?

**Comment by jmickael** [comment]
I solved this problem after spending many hours with Microsoft support and researching on google. What it came down to was refreshing the nonce cookie.  For it to work I had to keep my OWIN packages like this:
  package id="Microsoft.Owin" version="3.0.1" targetFramework="net45" />
  package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net45" />
  package id="Microsoft.Owin.Security" version="3.0.1" targetFramework="net45" />
  package id="Microsoft.Owin.Security.Cookies" version="3.0.1" targetFramework="net45" />
  package id="Microsoft.Owin.Security.OpenIdConnect" version="3.0.0" targetFramework="net45" />
I also implemented this package from Kentor:
  package id="Kentor.OwinCookieSaver" version="1.0.2" targetFramework="net45" />

The Kentor package makes sure the nonce cookie is refreshed keeping it small.  The version of the Owin packages is important for this solution to work so pay close attention to the versions from NuGet.
Then my app startup looks like this:
        public void ConfigureAuth(IAppBuilder app)
        {
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

            app.UseKentorOwinCookieSaver();
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                CookieSecure = CookieSecureOption.Always,
                ExpireTimeSpan = TimeSpan.FromMinutes(720),
                SlidingExpiration = true,
                CookieHttpOnly = true
            });

            app.UseOpenIdConnectAuthentication(
                new OpenIdConnectAuthenticationOptions
                {
                    AuthenticationMode = Microsoft.Owin.Security.AuthenticationMode.Active,
                    AuthenticationType = OpenIdConnectAuthenticationDefaults.AuthenticationType,
                    ClientId = ConfigHelper.ClientId,
                    Authority = ConfigHelper.Authority,
                    PostLogoutRedirectUri = ConfigHelper.PostLogoutRedirectUri,
                    UseTokenLifetime = false,
                    Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                        AuthorizationCodeReceived = context =>
                        {
                            try
                            {
                                ClientCredential credential = new ClientCredential(ConfigHelper.ClientId,
                                    ConfigHelper.AppKey);
                                string userObjectId = context.AuthenticationTicket.Identity.FindFirst(Globals.ObjectIdClaimType).Value;
                                string tenantId = context.AuthenticationTicket.Identity.FindFirst(Globals.TenantIdClaimType).Value;
                                AuthenticationContext authContext = new AuthenticationContext(ConfigHelper.Authority,
                                    new TokenDbCache(userObjectId));
                                AuthenticationResult result = authContext.AcquireTokenByAuthorizationCode(
                                    context.Code, new Uri(HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Path)),
                                    credential, ConfigHelper.GraphResourceId);
                                return Task.FromResult(0);
                            }
                            catch (OpenIdConnectProtocolInvalidNonceException e)
                            {
                                System.Diagnostics.Trace.WriteLine("ERROR.  OpenIdConnectProtocolInvalidNonceException e");
                                context.HandleResponse();
                                context.Response.Redirect("/Error/ShowError?errorMessage=OpenIdConnectProtocolInvalidNonceException Were having trouble signing you in&signIn=false" + e.ToString());
                                return Task.FromResult(0);
                            }
                            catch (AdalException e)
                            {
                                System.Diagnostics.Trace.WriteLine("ERROR.  AdalException e");
                                context.HandleResponse();
                                context.Response.Redirect("/Error/ShowError?errorMessage=AdalException Were having trouble signing you in&signIn=true" + e.ToString());
                                return Task.FromResult(0);
                            }
                            catch (GraphException e)
                            {
                                System.Diagnostics.Trace.WriteLine("ERROR.  GraphException e");
                                context.HandleResponse();
                                context.Response.Redirect("/Error/ShowError?errorMessage=GraphException Were having trouble signing you in&signIn=true");
                                return Task.FromResult(0);
                            }
                        },
                        AuthenticationFailed = context =>
                        {
                            System.Diagnostics.Trace.WriteLine("BEGIN CODE HANDLER AuthenticationFailed");
                            context.HandleResponse();
                            context.Response.Redirect("/Error/ShowError?message=" + context.Exception.Message);
                            return Task.FromResult(0);
                        },
                        SecurityTokenValidated = (context) =>
                        {
                            string userObjectId = context.AuthenticationTicket.Identity.FindFirst(Globals.ObjectIdClaimType).Value;
                            ClaimsIdentity claimsId = context.AuthenticationTicket.Identity;
                            List<String> groupMemberships = GetGroupsFromClaims(claimsId, userObjectId);
                            AssignRoles(userObjectId, groupMemberships, claimsId);
                            AssignCustomRoles(userObjectId, groupMemberships, claimsId);
                            return Task.FromResult(0);
                        },
                        RedirectToIdentityProvider = (context) =>
                        {
                            context.ProtocolMessage.Prompt = "login";
                            return Task.FromResult(0);
                        }

                    }
                });
        }

I haven't had that problem since.
Good luck

**Comment by RonniePitts** [comment]
Actually, you don't need to use Kentor. 

If you always have a login controller for Azure just check the cookies there and perform a cleanup. 

Basically, look for any OpenIdConnect.nonce cookie and set the expiry date in the end request. 

Problem solved.

**Comment by sudipster** [comment]
Just in case anyone is still looking for this: here is a solution which will preserve the last/latest 5 Nonce cookies and will delete any that are older that those. In order for this to work, ProtocolValidator.RequireTimeStampInNonce must be set to true in OpenIdConnectAuthenticationOptions.

https://github.com/IdentityServer/IdentityServer3/issues/1124

**Comment by devendracivica** [comment]
![image](https://user-images.githubusercontent.com/40286801/49583412-26fb5080-f97e-11e8-9ed6-34331e4ccb6b.png)
==========================================================
![image](https://user-images.githubusercontent.com/40286801/49583479-5b6f0c80-f97e-11e8-8e42-8b6a1edc268a.png)

We can We Can Make Custom Cookie Manager and Override the existing Nonce Cookie Provider. To Check the Cookie Collection Which not match with Current Key then Delete those cookie to avoid overflow of nonce cookie.And Configure that Cookie Manager to "UseOpenIDConnectAuthentication"
