### ISSUE TITLE
UnderstandingJwtBearerOptions RequireHttpsMetadata functionality

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#1825]
_From @tker on July 24, 2018 6:12_

We would  like some help understanding the functionality set by the JwtBearerOptions RequireHttpsMetadata boolean option.

[The documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.jwtbearer.jwtbeareroptions.requirehttpsmetadata?view=aspnetcore-2.1) for this option is somewhat sparse, and I have been unable to find a more complete description.

While the documentation states that this should only be set to false in a development environment, all of our services including the authentication (bearer token issuing) service operate exclusively behind a reverse proxy gateway, within which environment they are HTTP not HTTPS. 

The name of the option suggests that the token issuer needs to be an HTTPS endpoint; however, in our scenario this will not be the case.

Given the significance of proper security configuration I would like to know exactly what effect this flag has, how it works and what the implications of leaving it false in our scenario are.

We are not using OIDC or Identity, just the JWT bearer packages.

_Copied from original issue: dotnet/core#1812_

**Comment by Eilon** [comment]
_From @joshfree on July 24, 2018 19:7_

@Eilon could you help route this?

**Comment by blowdart** [comment]
@tker So ... generally token issuers are outside of your app, and in the case of federated services they can be outside your control (AAD, WSFed etc.), so for that most common use case we want HTTPS because then you know the request to get the signing keys for tokens isn't being intercepted or man-in-the-middled.

But sure, if you're doing everything internally I supposed it's arguably not needed, because if someone is at the point of MITMing your internal setup you have bigger problems. As the paranoid security person though, my feeling is even internal traffic should be using HTTPS in case your network does get breached, but that's a risk you're probably willing to take.

**Comment by Eilon** [comment]
Closing because no further actions are planned for this issue.

**Comment by tker** [comment]
Thank you for the responses received, but I am still unsure of the complete effects of this setting and precisely what it does. I had already formed the _opinion_  that in our scenario it is ok to leave false; however, I would much prefer a complete understanding of the setting's purpose, function, implementation and intent.

If this is not the appropriate place to find out not just exactly what it does, but how and why it works together with a detailed explanation of its implications within the described scenario (ie all services behind a proxy with no external access) where should I take it to find out?

**Comment by Tratcher** [comment]
Then see how it's actually used:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/d771b5c3ef22b7ff065e8fad1a63d6a2937b7d7f/src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs#L69-L89

It is only checked for downloading metadata documents.
