### ISSUE TITLE
Basic auth

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Security#209]
Is there an auth middleware for Basic auth ? I know it's for Active Directory and OAuth but I always end up writing my own basic one.

Can this will be implemented in the aspnet packages ? Maybe I'm missing it. think I would be a good addition to current auth middlewares.

**Comment by blowdart** [comment]
We've considered it, but as it's such an awful standard from a security perspective, and can only be made safe by use of SSL we're not inclined to provide one as it's a route to failure.

**Comment by Bartmax** [comment]
why don't make it fail or warning when there's no SSL ? Is it really that bad even with SSL ?

**Comment by davidfowl** [comment]
This are the sorts of questions that make us not want to provide it out of the box :smile:

**Comment by blowdart** [comment]
Shipping something that fails by default generally upsets everyone.

Even if we limited it to SSL only you end up having to hash and then compare the password against a source with every request. If your password database is doing it's job well that's not a speedy operation, and so with relatively few basic auth requests compared to cookie auth you're filling the machine's CPU with hashing.

**Comment by davidfowl** [comment]
Every http stack has this. Maybe we should as well. The limitations are well known.

**Comment by blowdart** [comment]
If every HTTP stack threw itself off a bridge would you want DNX to follow?

We made a specific decision not to support basic auth last year. My attitude has not changed.

**Comment by davidfowl** [comment]
Sample then?

**Comment by blowdart** [comment]
Sample works. With huge caveats all over the place of "Using this for any sort of production site will make blowdart cry".

**Comment by davidfowl** [comment]
Should we put it in the security repository or entropy?

**Comment by blowdart** [comment]
Entropy => Elsewhere ? (I don't think put it here, because that's more of a blessing than I'd feel comfortable with)

**Comment by Bartmax** [comment]
looks like very emotional response @blowdart, you are assuming that the app will have multiple request, you assume that I will have multiple calls per user, you assume the password is hashed on a database, sounds like you are assuming a lot of things actually.

I'm not security expert, but if you assure that basic auth isn't an option for any of the wide range of web apps usecase, then I trust you.

just keep in mind that a jump from a bridge could be a very valid option (see banging jumping).

**Comment by Kukkimonsuta** [comment]
It would be nice if it was supported out of the box, since there are still real world cases where it's useful (like protecting staging environments), but I guess we can live without it since it's pretty easy to implement anyways - I gave it a shot taking cookie auth as template, so if anyone's interested: [Odachi.Security.BasicAuthentication](https://github.com/Kukkimonsuta/Odachi/tree/master/src/Odachi.Security.BasicAuthentication).

I understand why you don't want to include it, however I don't believe in "protecting" developers/users by not implementing some features. Every tool has it's uses, both good and bad and the bigger toolbox the better.

**Comment by ctolkien** [comment]
For what it's worth, we often use basic auth for things that are a "little" bit secret (like the above mentioned staging sites).

**Comment by Eilon** [comment]
@blowdart do you want to write a sample for this?

**Comment by brockallen** [comment]
https://github.com/leastprivilege/BasicAuthentication.AspNet5

**Comment by blowdart** [comment]
@Eilon or we just link to a couple of the community implementations ...

**Comment by Eilon** [comment]
Anything is fine with me :smile: 

Should we link from the readme?

**Comment by blowdart** [comment]
Yea sure, make it so number 2

**Comment by Eilon** [comment]
Riker is vacationing on Risa, so this issue is assigned to you, @blowdart .

**Comment by blowdart** [comment]
I shall deal with it during airport layovers tomorrow then. I suppose you're more of a Troi anyway

**Comment by HaoK** [comment]
Ouch

**Comment by Eilon** [comment]
Not possible. My empathy for you is... not there :smile:

**Comment by jon49** [comment]
For legacy applications what would be the best route if we can't use Oauth2. The company I work at has a server that validates the username/password and tokens that were returned on sign in. But it isn't externally facing. So, I basically need to build an Oauth2 and Bearer style authentication into my server. But Oauth2 doesn't make sense if it's the same server. Since I'm dealing with iOS apps and not the web cookies don't make sense either.

I haven't seen anything point in the right direction on how to properly get this done. I'm sure it's out there, just can't find it.
