### ISSUE TITLE
Possible Race condition in when checking nonce cache

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#317]
The nonce checking is in two parts:
It is possible that multiple GetAsnyc occur before the Set.

```c#
if (await Options.NonceCache.GetAsync(message.Nonce) != null)
{
    Logger.LogError(Resources.OIDCH_0033_NonceAlreadyExists, message.Nonce);
    throw new OpenIdConnectProtocolException(string.Format(CultureInfo.InvariantCulture, Resources.OIDCH_0033_NonceAlreadyExists, message.Nonce));
 }

 await Options.NonceCache.SetAsync(message.Nonce, new byte[0], new DistributedCacheEntryOptions
 {
 AbsoluteExpirationRelativeToNow = Options.ProtocolValidator.NonceLifetime
  });
```

**Comment by PinpointTownes** [comment]
This is not new: the same race condition could occur with `INonceCache`.
And AFAIK, there's no way to prevent it, specially in a distributed environment.

**Comment by brentschmaltz** [comment]
With a single atomic call, you can guarantee that only one will succeed. Which is why I originally designed it with a single sync call.
That is how distributed databases work. From the runtimes POV, there is no difference between the first and subsequent calls. Important thing is only on will succeed.

**Comment by PinpointTownes** [comment]
> With a single atomic call, you can guarantee that only one will succeed. Which is why I originally designed it with a single sync call.

`INonceCache` had no default implementation, so it's very theoretical :smile:  
And even if you have only one method, you can't guarantee that the implementer designed it to be really atomic.

> That is how distributed databases work.

I wouldn't be that general: it depends on whether the database supports ACID transactions and on the specific isolation level you choose. To support atomic transactions, I guess aspnet/Caching would have to be completely revamped, which is probably unlikely to happen. The SQL provider would certainly support that, but not the in-memory cache.

If you're really afraid of collisions, updating `GenerateNonce` to add more entropy (using a RNG provider) might also be an option.

/cc @Tratcher

**Comment by brentschmaltz** [comment]
@PinpointTownes the point is the design allowed for a ACID implementation. I don't think a two step async model can.

**Comment by Eilon** [comment]
We're not sure how this could be a problem - how can the same nonce be generated more than once?

Closing because we don't think this can happen.

**Comment by PinpointTownes** [comment]
> We're not sure how this could be a problem - how can the same nonce be generated more than once?

Actually, nonce collision is not the problem here. The whole point of ensuring nonce cookies are unique is to avoid replay attacks. With the design we have (that involves no locking and is in 2 parts), we can't really guarantee that 2 requests using the same nonce and arriving at the same time won't both allow their respective user (a legit user and a bad guy) to be correctly logged in.

**Comment by Tratcher** [comment]
The code referenced above is from HandleUnauthorizedAsync when the nonce is initially generated and sent. In theory you shouldn't be generating duplicate nonces, so the Get check is more of an assert.
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationHandler.cs#L203-L215

The nonce validation code https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationHandler.cs#L957-L960 does have a small race between checking if the nonce is cached and removing it. However, that's not a race that can be deterministically avoided when using distributed caches.

**Comment by PinpointTownes** [comment]
I agree, `ProtocolValidator.GenerateNonce()` is supposed to offer enough entropy to avoid collisions when generating a new token and since we have no way to use locking with `IDistributedCache`, we can't really prevent a race condition when validating the nonce.

I was just reacting to the fact this ticket was closed with the "invalid" label - implying @brentschmaltz's question was not correct - and not with the "wont-fix" label, that would indicate that you were aware of this potential "bug" but that there was also no reasonable way to fix it.
