### ISSUE TITLE
The ClaimsPrincipal created by the Authentication Layer is not preserved as created to the Application Layer.

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#323]
The ClaimsPrincipal that is created by an Authentication Middleware is not preserved as created. Users who are developing using CustomPrincipals will loose any context.

**Comment by leastprivilege** [comment]
Custom principals should not be supported. Identities are made up of a collection of claims - and nothing else. Any OOP sugar you want to add to it should be done at the application level - not the framework level.

**Comment by brentschmaltz** [comment]
@leastprivilege Some users have made use of custom principals, I am curious as to why you think CustomPrincipals are not important.

I am bringing up for discussion that after an AuthenticationHandler has created a CP and returned an AuthenticationTicket, the runtime breaks apart the AuthenticationTicket and merges the contents of the CP into a new CP, sometimes dropping things.

Assuming the AuthenticationHandler is authoritative for the identity (understanding the procotol), I am questioning why the layers above should modify the identity.

**Comment by PinpointTownes** [comment]
Personally, I've always considered that creating extension methods around `ClaimsPrincipal`/`ClaimsIdentity` was easier and more flexible when everything they were doing was formatting a specific claim value (e.g `GetUserId()`, `GetAccessToken()`), but this is a fact we can't deny: a non-negligible number of users WANT to create their custom `ClaimsPrincipal` (the question has been asked many times on JabbR), and that's why I'd tend to agree with @brentschmaltz.

There are currently two main friction points:
* `SecurityHelper.MergeUserPrincipal` (https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication/SecurityHelper.cs#L22): I guess we would have to update it to avoid creating a new `ClaimsPrincipal`. It should probably reuse `existingPrincipal` and directly call `existingPrincipal.AddIdentities(additionalPrincipal.Identities)`.

* `TicketSerializer` (https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication/DataHandler/Serializer/TicketSerializer.cs): probably the most complicated part. Maybe we should simply add new protected virtual methods to allow modifying the logic used to serialize/deserialize `ClaimsPrincipal`.

On the other hand, I'm convinced we should continue exposing `ClaimsPrincipal` in all the authentication APIs. Adding generics here would be really messy. Users wanting to use a custom `ClaimsPrincipal` will have to "pay" for it, by casting their principals :smile: 

@brentschmaltz I guess you'd also like to support `ClaimsIdentity` and `Claim` subclasses?

**Comment by leastprivilege** [comment]
@brentschmaltz I am not saying ClaimsPrincipal is not important - but in my mind the (claims) principal is simply a container for claims (plus some metadata like properties if need be ;)) and thats what should be serialized / round tripped - not type information. Anything else can be built on top of that.

One of the design goals behind claims principal was to create the "one principal to rule them all" - no more special case implementations.

That said - I can totally see the use case for "extra functionality" on top of the raw claims principal - and agree with @PinpointTownes here that extensions methods or composition are much better suited.

So why not educate the non-negligible number of users how to do it right instead of building a hideously complex feature that only a subset of the them actually need. Or put it in the backlog for a vNext. Unless your backlog is currently empty ;)

If I learned one thing during the last 10 years of claims in the .net framework - it is "keep it simple, stupid".

my 2c.

**Comment by HaoK** [comment]
@lodejard and @blowdart should probably chime in on this one too.

My thinking has pretty much been along the lines of @leastprivilege where the authentication handler contract is primarily the collection of claims identities being provided (with the principal really just being a container), with no guarantees on anything else.  I don't think instance/type preservation is worth the complexity since people can certainly build that complexity themselves via the the various extension points that exist already today.

@PinpointTownes Previous iteration of the helper used to do exactly that (just append existing claims identities onto the new claims principal)  I forget exactly that rational for the change (which I made fairly recently beta5ish I think), but I think we wanted to explicitly break that behavior (@lodedej might remember the exact reasoning)

**Comment by brockallen** [comment]
Isn't this what claims transformation should do? In short, it should be kept simple.

**Comment by blowdart** [comment]
My chime is that custom principles is so much work for an edge case that no-one can actually give me numbers on. I don't know if it's .01% of users or 1% and frankly, even at 1% I'm not sure I care, when extensions are cleaner and easier to maintain and more in the asp.net way of doing things.

**Comment by damianh** [comment]
Composition > Inheritance trumps just about every time.

:-1: from me on the concept of `CustomPrincipals`

(current status: unwinding an ICompanyPrincipal in an app.)

**Comment by leastprivilege** [comment]
+1 for @brockallen , @blowdart and @damianh

**Comment by PinpointTownes** [comment]
> Isn't this what claims transformation should do? In short, it should be kept simple.

> I don't think instance/type preservation is worth the complexity since people can certainly build that complexity themselves via the the various extension points that exist already today.

Except that currently, if you set a custom principal from one of the notifications we offer or if you return a custom principal from an authentication handler (from the claims transformation middleware for instance), it MAY silently disappear in the middle of the pipeline (mainly because of `SecurityHelper.MergeUserPrincipal`, but it's not the only culprit: the authorization layer will also replace `HttpContext.User` if you use `ActiveAuthenticationSchemes`).

I'm not saying that custom principals should be encouraged, just that we shouldn't make this scenario impossible by replacing `HttpContext.User` if we can find a reasonable way (i.e a few lines of code at least) to make their lives less miserable :smile:

**Comment by brentschmaltz** [comment]
Couple of things we should probably consider.

1. Do we want to support IsInRole and Integrated Windows Auth?
IsInRole is interesting because of the dynamic nature of determining if a user is in a 'role'. Currently, .Net RolePrincipal uses a RoleProvder to help resolve the IsInRole question. 

Plain-Jane, ClaimsPrincipal queries each ClaimsIdentity for a 'roleClaim' match. 
Not all IsInRole queries can rely on the ClaimsIdentity having a claim since not all IDP's return all the role claims. In particular AzureAD is not guaranteed to return all role or group claims. In fact, you probably wouldn't want them in the CI as the size would become large, increasing our already large cookies. I suppose we could OR ask users to develop a DynamicRoleClaimsIdentity, but that would be dropped during serialization. ClaimsIdentity has been designed to work with DynamicRole providers with the contract: if ClaimsPrincipal.IsInRole("bob") == true IFF for one of the ClaimsPrincipals identities HasClaim(ClaimsIdentity.RoleClaimType, "bob") is true.

WindowsPrincipal knows how to communicate with the NTToken within AD SecurityDomains.
We should consider if we need / want these scenarios.

2. The contract for creating the identity is between the Identity Provider, SecurityTokenValidator and TokenValidationParameters (TVP is normally obtained form IDP metadata).

The translation of the 'signin' message from the IDP into an app consumable object has been specified by the developer. The developer has decided on what the Identity should look like. Why should the identity change between the time it was created and it is presented to the application layer?

3. I am not advocating to replace HttContext.User. I am suggesting that the artifacts (AuthorizationTicket)  that are a result of 'Authorize' be presented to a 'ClaimsTransformation' point as they were created, to give the developer a centralized location where they can make a comprehensive decision on what HttpContext.User should be.  By default we can do something reasonable.

4. Chopping things up (pushing parts of the AuthorizationTicket up the stack and rehydrating it later), making arbitrary decisions (if ClaimIdentity.Authenticated is false then do not add it to the newly created ClaimsPrincipal. Even though it was returned in the AuthorizationTicket from Authorize - are we saying Authorize made a mistake?), reordering the ClaimsIdentities (IsAuthorized may fail because of some implementation detail) work against a framework being flexible.

**Comment by blowdart** [comment]
Leave Windows Auth alone. It stays as is.

It's too late to start trying to entirely rearchitect something that is part of CoreCLR anyway.

**Comment by brentschmaltz** [comment]
It is up to the asp.net team to make the call here. Said all I can say about this.

**Comment by Eilon** [comment]
Custom claims principals are not supported in ASP.NET 5.
