### ISSUE TITLE
Why does AuthenticationHandler.AuthenticateAsync(...) call ShouldHandleScheme

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#337]
If OIDC handler AutomaticAuthentication == false, then context.AuthenticationScheme must == options.AuthenticationScheme for OIDC.AuthenticateAsync to be called.

How does AuthenticationContext.AuthenticationScheme get set, before the call to AuthenticateAsync(...)?

**Comment by HaoK** [comment]
Some of the confusion might be due to the naming fail we have today where we have two AuthenticateAsync methods which differ by access/parameters and return type only.

1. The public non virtual one which is used by Http/Auth which handles caching/calling into the second abstract one.

2. The protected abstract one that actually creates the AuthenticationTicket.

I'll rename these so its not so insane

**Comment by HaoK** [comment]
The caller of Authenticate says what scheme he wants before calling authenticate.

Rename issue is here: https://github.com/aspnet/Security/issues/341
