### ISSUE TITLE
[OIDC] Redesign or remove nonce cookie support

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#390]
The nonce used during the OIDC login can be stored in a cookie or in a server side cache. The cookie support is buggy and needs to be redesigned or removed.

A simple cookie name cannot be used because it will overwrite the existing cookie if a login flow is in progress in another browser tab. To address this a unique cookie name was used per login.

Now the problem is knowing when to clean up stale cookies since we can't tell if another browser tab is still open and will eventually complete it's login flow.

The most often reported problem is in scenarios with configuration issues where the client gets into a redirect loop and creates additional nonce cookies until they get a 400 from the server saying there are too many headers. In this case the surplus of nonce cookies are a just symptom of a configuration problem and no amount of cleanup effort is likely to make the scenario succeed.

RE: https://github.com/aspnet/Security/issues/179

**Comment by nenadvicentic** [comment]
Regarding one of the issues with Nonce cookie:

> IDX10311: RequireNonce is 'true' (default) but validationContext.Nonce is null. A nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'.

There is a case where cookie does not get written in the HTTP response at all. And it's easy to reproduce.

In MVC controller's action (ex `/account/login`), I have 2 lines of code:

    
    httpContext.Session.Abandon(); // Cause of the problem!
    
    context.Authentication.Challenge(
    	new AuthenticationProperties(),
    	OpenIdConnectAuthenticationDefaults.AuthenticationType);
    
I first abandon current `Session` and then call `Authentication.Challenge()` to redirect user to authorization server.

As a consequence of **abandoning the session**, ASP.NET pipeline does not output `Set-Cookie: OpenIdConnect.nonce...` in the redirect response, even though it was previously set by `CookieManager`.

Browser never receives the cookie. After user gets redirected back from authorization server to the relying party, cookie is not there and `nonce` validation fails.

If I replace `Session.Abandon()` with `Session.Clear()` everything works fine.

Core of the issue seems to be related with handling of `Response.Headers` in the Microsoft ASP.NET pipeline, which has some known issues.

*IMPORTANT - To reproduce issue delete ASP.NET session cookie before hitting the page! When cookie is present, example works.*

**Comment by Tratcher** [comment]
@nenadvicentic that is only applicable to Asp.Net 4 / MVC 4 / Katana. Session.Abandon() no longer exists in Asp.Net 5. See http://katanaproject.codeplex.com/wikipage?title=System.Web%20response%20cookie%20integration%20issues&referringTitle=Documentation

**Comment by Tratcher** [comment]
Recommendation: Mitigate by setting a default cookie timeout for 15 minutes.

**Comment by johnkors** [comment]
Will this fix be in any of the v.3.* -packages of `Microsoft.Owin.Security.OpenIdConnect` as well, or what is the plan exactly here..? 

We're currently being forced to downgrade to `3.0.0` from `3.0.1` because of this.

**Comment by Tratcher** [comment]
@johnkors Given the imminent release of Asp.Net Core there's no plan to backport this change to the Microsoft.Owin packages.

**Comment by rseso** [comment]
@Tratcher If the bugfixes are not being backported to the Microsoft.Owin packages, what is the roadmap for the OWIN in ASP.NET (not Core)? Is there any replacement for it that is being actively maintained?

**Comment by davidfowl** [comment]
Super old blog post but it gets the point across still I think https://blogs.msdn.microsoft.com/webdev/2014/11/14/katana-asp-net-5-and-bridging-the-gap/.

**Comment by rseso** [comment]
@davidfowl Thanks, so if I got it right, we don't have any 1:1 replacement for the Microsoft.Owin stack and packages being actively maintained for the "classic" .NET, right?
