### ISSUE TITLE
Extremely simple auth?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Security#395]
What's the simplest way of doing authentication? I have a site where there'll only ever be one user (me) and I'm happy editing a config file to change my password. The 'regular' auth options (database as well as third-party services like Facebook and Twitter) seem like overkill for this particular use case, I just some something small and light.

Currently with ASP.NET 4 and MVC 4, I use Forms auth with the [credentials section in Web.config](https://msdn.microsoft.com/en-us/library/532aee0e(v=vs.71).aspx). Is there something equivalent for ASP.NET 5? I saw in the readme that Basic authentication is not included, but is there something similar to Forms cookie authentication with a flat file list of usernames and hashed passwords?

**Comment by Eilon** [comment]
Let's start out with the difference between *identity* and *authentication*. Identity is about remembering who is who. Authentication is about deciding whether somebody is really who they say they are. (And lastly, authorization is saying whether someone has access to a particular resource or operation.)

I think in you case it sounds like you still want forms authentication with cookies. But perhaps you want a simple *identity* system that knows about just you.

You could certainly build an app in ASP.NET 5 that uses the regular identity system and the regular forms auth cookie system, but on app startup adds the one special user (you). You would likely want to check whether "you" already exist, and only if not, insert a new "you" with a particular password into the system.

As to where you store the password of "you," well, I certainly wouldn't recommend storing it in a config file in plaintext because that would make the system highly vulnerable to an attack. It also means that the password is in source control, which is all kinds of bad. If the web server has a location for storing secrets (e.g. Azure has secret storage), I would place the password there, and read the value on app startup.

**Comment by Daniel15** [comment]
>  It also means that the password is in source control, which is all kinds of bad.

My current setup (on ASP.NET 4) is that I have the username and password in an `Authentication.private.config` file, and my `.gitignore` has `*.private.config` in it. This is what I have checked in to source control:
```
<?xml version="1.0" encoding="utf-8" ?>
<authentication mode="Forms">
	<forms loginUrl="~/Account/Login" timeout="2880">
		<credentials passwordFormat="SHA1">
			<!-- Example login is username "example" and password "password". CHANGE THIS!! -->
			<user name="example" password="5BAA61E4C9B93F3F0682250B6CF8331B7EE68FD8" />
		</credentials>
	</forms>
</authentication>
```

I import that into Web.config via `<authentication configSource="Authentication.private.config" />`. My deployment script ignores all *.private.config files, and I just edit them on the server directly.

Given this is just for a small personal site, I'm not really worried too much about making it super secure.

> but on app startup adds the one special user (you)

By "add", do you mean adding to some in-memory password store? I haven't actually looked into ASP.NET's identity stuff yet.

**Comment by Eilon** [comment]
Yeah you could certainly have a source-control-ignored file where you store it.

For identity you could certainly have a custom storage provider that is in-memory or reads from a disk.

Or, use the built-in store that uses Entity Framework 7 and at app startup create the new user with the password.

**Comment by Daniel15** [comment]
Is there an example in-memory provider (or does ASP.NET 5 come bundled with one)?

> Or, use the built-in store that uses Entity Framework 7

I'm still using EF6 since I use MySQL (which doesn't have an EF7 provider yet).

**Comment by Eilon** [comment]
There's some stuff in the [Identity repo](https://github.com/aspnet/Identity). Check out the [Startup](https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.Mvc/Startup.cs#L96-L97) code, which uses a [sample data](https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.Mvc/Models/SampleData.cs) helper class.

**Comment by Daniel15** [comment]
Thanks for your help :+1:

**Comment by Daniel15** [comment]
@Eilon - Is there an identity package that doesn't depend on Entity Framework 7? All the examples I'm finding reference `Microsoft.AspNet.Identity.EntityFramework`, and `Microsoft.AspNet.Identity.Core` doesn't look like an ASP.NET 5 package.

**Comment by Daniel15** [comment]
Never mind, it was just NuGet's search being broken again:
![screen shot 2015-08-08 at 12 46 12 am](https://cloud.githubusercontent.com/assets/91933/9149621/015563ba-3d67-11e5-863f-29c29ef4f6fd.png)

I found `Microsoft.AspNet.Identity` and just installed it via the Package Manager console instead.

**Comment by Eilon** [comment]
There's ASP.NET Identity for ASP.NET 4.x, and ASP.NET Identity for ASP.NET 5.x - the two are not compatible - just make sure you're using the right one.

**Comment by Daniel15** [comment]
Thanks for your help, I put together something extremely simple for my use case: https://github.com/Daniel15/SimpleIdentity
