### ISSUE TITLE
Split CookieAuthenticationEvents "ApplyRedirect" into multiple events

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#458]
Split the current "ApplyRedirect" into multiple events depending on what is being redirected to. New names shouldn't have the word "Apply" in them, they should use the pattern RedirectToXyz.

**Comment by jods4** [comment]
:+1: 
I have just been bitten by this design change (initiated when CookieMiddleware started to always redirect in b883920).

A few comments:

Although I'm watching the Notifications repo, I didn't see an announcement about that and beta-7 was a breaking (at runtime) change for me because redirect would still happen when `options.LoginPath` was set to `null` (until beta-6 that's how you prevented redirects). Unless I missed the announcement, I think this is worthy of more communications.

Configuring the redirects for _not_ happening is a valid if not common scenario in Web API (an AJAX call cannot use a login HTML page...).

I found out that the new way to do this is to change `OnApplyRedirect` in `options.Notifications` (beta-7, now renamed to `options.Events`). That's fine but it could be better for 2 reasons:

1. `OnApplyRedirect` is very generic and the reason "why" is lost, which makes coding this handler more difficult (was it 401, 403, something else)? I think it should be split in more specific cases and this is what this ticket is about.

2. `OnApplyRedirect` is not part of the `ICookieAuthenticationNotifications` (renamed post beta-7) interface, which is what `options.Notifications` exposes. This means that overriding the behavior requries an unwieldy cast: `((CookieAuthenticationsNotifications)options.Notifications).OnApplyRedirect = ...`. It is also hard to discover when you look for a way to configure redirects in the IDE. 
Maybe you should extend the interface, or if you don't want to expose the `OnXYZ` to interface consumer, expose `CookieAuthentificationNotifications` to options only.

**Comment by Tratcher** [comment]
@jods4 as for 2, the recommended way to override it is:
```
options.Notifications = new CookieAuthenticationNotificatoins()
{
 OnApplyRedirect = ...
}
```

**Comment by jods4** [comment]
@Tratcher thanks for the tip!

**Comment by jods4** [comment]
BTW it would be nice if the _default_ behaviour when `OnApplyRedirect` does nothing was to return 401 / 403. I mean: currently the default `Events.OnApplyRedirect` sends an HTTP redirect to `LoginPath` but if you remove it then the server returns a plain 200 with no content.

My thinking is: the request was unauthorized, so it should start as a 401. That makes sense. 
Now if ASP.NET wants to set a default `OnApplyRedirect` that transforms 401 into a `LoginPath` redirect I'm fine with that, _but_ when I remove it I would like to have the 401 behaviour pass through.

My observation is that if you put an empty method in `OnApplyRedirect` you get a 200 OK, which makes little sense in this context by default. You currently (beta-7) have to hack `context.RedirectUri` to decide whether it's a 401 or 403 and actually set the `context.Response.StatusCode` to that.

**Comment by Tratcher** [comment]
Cookie/forms auth only defines redirects and should not produce 401s or 403s, those are defined by standard HTTP auth (e.g. basic, bearer, etc.).

The guideline for WebApi scenarios is to challenge for something specific like bearer, bypassing cookie auth entirely.

**Comment by jods4** [comment]
> The guideline for WebApi scenarios is to challenge for something specific like bearer, bypassing cookie auth entirely.

I am not talking public internet-style web API here. I am talking private, secure, intranet web API that is back-end for a web application. Users have to log in the application using username and password. Server calls are limited by their personal rights and must be revokable when they log out or close their browser.

If by bearer you mean (from RFC 6750):
> Bearer Token
      A security token with the property that any party in possession of the token (a "bearer") can use the token in any way that any other party in possession of it can.  Using a bearer token does not require a bearer to prove possession of cryptographic key material (proof-of-possession).

Then I think it is absolutely not what my web API needs. I am curious if you have other ideas, but as far as I know cookie auth. seems to be the most adequate auth. primitive that ASP.NET offers me. 

I also think that in this context, a request denied because of insufficient privileges should return 401 or 403 to the browser. Returning an empty 200 OK is just wrong and returning a redirect to an HTML login form is inappropriate for AJAX calls. I don't mind that the latter is the default, but .NET had a philosophy of being a "pit of success" where doing things the obvious way would "just work". Removing the redirect code ends up in a situation that does not make sense to me. 

_Before_  b883920, when you set `LoginPath` to `null` you would disable the redirect and get a 401 instead, it seems to me that it made sense.

I don't think this is an uncommon scenario. I work at a large IT company and have been for a decade. We built lots of web apps or fat clients back-ends with just web services. Web API is remarkably well suited for that.

**Comment by Tratcher** [comment]
username and password API login is commonly handled by 'Basic' auth or Windows auth (NTLM).

**Comment by jods4** [comment]
Windows auth is great for that kind of scenarios and I use it whenever I can. But sometimes (like my current case) it is not feasible.

Basic auth is an option but it's not great. Username and password must be sent and verified on each requests, logging out is hacky. The web app must manage the credentials (and keep the username in JS memory) because it has to manipulate each request to include auth. If you let the browser do that, I believe you have little control over the credential caching time (can be as short as 15 minutes) and no control over the log on UI? (I might be wrong on the last one)

**Comment by Tratcher** [comment]
@blowdart Want to pick this one up?

**Comment by blowdart** [comment]
For pit of success we try to steer away from cookie auth for apis because of CSRF. 

Maybe the old effect could be configurable though, for back compat if you really want and understand the risk.

**Comment by jods4** [comment]
@Tratcher @blowdart Please note that the discussion went off on a tangent a bit.
At first I was just commenting on the new APIs design to configure cookie auth. middleware.
In the end, I can make everything work as I want to, so no blocker here.

The point I was making initially was:
- Yes, splitting `ApplyRedirect` or making its cause easily identifiable is required (this ticket basically);
- It is a bit disconcerting that putting a no-op in `OnApplyRedirect` ends up with a 200 OK request, since (a) this is not 200 OK obviously and (b) previously you could get the 401 back when you put `null` into `LoginPath`.
- The API for configuring this is not very discoverable, as the option can not be found by IntelliSense (you have to know which class to instantiate (or cast to) to get the actual option).

**Comment by Tratcher** [comment]
The old effect is already achievable by setting the status code in OnApplyRedirect.

**Comment by jods4** [comment]
@blowdart 
A web API for an internal application can easily include a CSRF token, can't it? I intend to do that but haven't configured ASP.NET 5 to achieve that. I was thinking of sending the CSRF token to the application at startup and then put it in every AJAX request header.

**Comment by jods4** [comment]
BTW thanks for the tips, I will think about Basic Auth and maybe reconsider a bit. 
It is true that it removes CSRF requirements and I could just keep the user+password base64 string in the app and send it in a header with every http request. 
Only downsides I see is 3rd party components who make their own requests and having to validate the password each time, which is (by design) expensive.

**Comment by blowdart** [comment]
CSRF for webapi involves embedding a form, yanking the token out of it and sending it with every request. At that point you may as well have switched to bearer :)

**Comment by blowdart** [comment]
(And basic is just as vulnerable to CSRF, as once the browser has logged it it'll flow automatically like cookies)

**Comment by jods4** [comment]
@blowdart 
> At that point you may as well have switched to bearer

Are you serious?
Bearer does not identify the user. Username + password does.
The point of CSRF token is not sending it in the URL to prevent crafting links or img sources or whatever.
Did I miss something here?

> And basic is just as vulnerable to CSRF, as once the browser has logged it it'll flow automatically like cookies)

Indeed. I was mislead  when Tratcher said recommendation for APIs were Win or Basic and you said
> we try to steer away from cookie auth for apis because of CSRF

I kinda assumed that Basic was better than Cookie in this regard, but indeed if the browser sends it automatically from its cache then it's no better.

**Comment by blowdart** [comment]
I'm not saying bearer identifies the user (although if you used a jwt it could, validate signature instead of password). In middleware you'd validate and exchange the bearer token for a principal. 

CSRF tokens go into a form and are linked to the user, or the browser by a secondary cookie. They are there to stop someone crafting a form and hosting it on another web site, then submitting the form to yours (and tricking your users into doing something on your site they didn't initiate)

**Comment by jods4** [comment]
> In middleware you'd validate and exchange the bearer token for a principal. 

That's more or less what the cookie is/does, isn't it? Except cookies are managed by the browser.

> CSRF tokens go into a form and are linked to the user, or the browser by a secondary cookie. They are there to stop someone crafting a form and hosting it on another web site, then submitting the form to yours (and tricking your users into doing something on your site they didn't initiate)

I think that I understood your previous statement incorrectly:
> At that point you may as well have switched to bearer

I thought you meant that sending a CSRF token in a HTTP header with every request was no more secure than authentication with a bearer token. Did you in fact mean that in the situation I describe sending a constant bearer token in a HTTP header was good enough to prevent CSRF on the web API? That the whole CSRF token thing was more complicated because it protects different scenarios?

**Comment by blowdart** [comment]
> That's more or less what the cookie is/does, isn't it?

Yes, that's exactly what the cookie middleware does.

> That the whole CSRF token thing was more complicated because it protects different scenarios?

ah no, what I'm saying is the effort to write script to pull a CSRF token out, put it into a header, and then check it on the other end is close to the effort needed to write a bearer token issuance and parser that with very little effort you could go the bearer token route.

**Comment by jods4** [comment]
I see.
Thanks again, I'll stop here because I think we have moved rather far away from the issue topic. <_>

**Comment by blowdart** [comment]
:)

**Comment by HaoK** [comment]
https://github.com/aspnet/Security/pull/482
