### ISSUE TITLE
Clean up notification extensibility model

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#47]
The original batch of social auth middleware (Facebook, Twitter, etc.) all used three different extensibility models for their notifications (formerly Providers).  There was an `I*AuthenticationProvider` interface with methods and a *AuthenticationProvider class defining both virtual methods to be overridden and `On*` settable delegates. The second round (WsFed, ODIC) got rid of the interface and virtual methods, leaving only the settable delegates. Note you could still derive from the notification class, you would just need to set the delegates in your constructor.

**Comment by HaoK** [comment]
@PinpointTownes does your PR address everything here?

**Comment by PinpointTownes** [comment]
@HaoK not really. This ticket was about unifying `I*AuthenticationProvider` and `*AuthenticationNotifications`, but `I*AuthenticationProvider` has since been replaced by `I*AuthenticationNotifications`.

The question is now: do we want to have...
* an `I*AuthenticationNotifications` interface and a default `*AuthenticationNotifications` class exposing `Func` properties like the OAuth2 client middleware https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OAuth/Notifications/IOAuthAuthenticationNotifications.cs and https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OAuth/Notifications/OAuthAuthenticationNotifications.cs
* or a single `*AuthenticationNotifications` class that doesn't have any method and simply exposes `Func` properties, like the OIDC client middleware: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationNotifications.cs

The first approach is definitely less DRY but seems more flexible and allows advanced scenarios like interface interception via Dynamic Proxy.

**Comment by Tratcher** [comment]
I recommend the second approach. It's much cleaner and I have never seen anyone utilize the extensibility provided by the first approach.

**Comment by PinpointTownes** [comment]
@Tratcher here's a sample of subclassing a default `*AuthenticationProvider` class: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/samples/Mvc/Mvc.Server/Providers/AuthorizationProvider.cs#L11

Overriding a method is much cleaner that assigning a delegate.

**Comment by anurse** [comment]
@HaoK We need to do design on this. @glennc can assign an existing design meeting slot for this.

**Comment by PinpointTownes** [comment]
Do we finally have an agreement on the definitive notification pattern?

(related topic: https://github.com/IdentityServer/IdentityServer3/issues/1437)

**Comment by Tratcher** [comment]
Nope...

**Comment by Tratcher** [comment]
Notes:
- Rename *Notifications -> Events
- Change OIDC notifications -> use the I*Notifications pattern (see cookies)
- Move all of the OIDC base notification objects from Authentication/Notifications to ODIC/Notifications, squash the <TMessage> generic. Rename to *Context.
- Rename OAuthBearer to OAuthJWTBearer or something similar? Its not generic bearer, it’s JWT IdentityModel bearer.

I’ll file separate bugs for these.

**Comment by Tratcher** [comment]
Filed https://github.com/aspnet/Security/issues/413 for OAuthBearer. The others are all interrelated and can be handled together as part of this #.

**Comment by PinpointTownes** [comment]
Nice! :+1:

**Comment by Tratcher** [comment]
Related: https://github.com/aspnet/Security/issues/307
