### ISSUE TITLE
Define central claims transformation point

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#48]

**Comment by brentschmaltz** [comment]
I agree we need a single point to evaluate what the 'user' should look like when all of the AuthenticationMiddleware (s) have completed. Since the ISecurityTokenValidator returns a ClaimsPrincipal and is configurable by the user, we need to maintain the object the user returned.

The AuthenticationHandler returns an AuthenticationTicket, if this is preserved and accessible then this would allow complete extensibility.

**Comment by HaoK** [comment]
Discussed as part of the AuthN changes, going to go with a ClaimsTransformationMiddleware which uses a ClaimsTransformationOptions to:

1: Apply transformation to the HttpContext.User as part of the pipeline
2. Also hooks any calls to HttpContext.AuthenticateAsync to apply transformation before returning the resultant identity
