### ISSUE TITLE
External login info is always null with GitHub

### ISSUE THREAD

**Issue by Haythem** [aspnet/Security#507]
I'm trying to implement GitHub login within Owin. Everything is good until the `ExternalLoginCallback` on the `AccountController` gets hit. The `_signInManager.GetExternalLoginInfoAsync()` always returns null.

Here's my implementation of the provider in the `Startup` class :
```csharp
app.UseOAuthAuthentication("GitHub", options =>
{
        options.AuthorizationEndpoint = "https://github.com/login/oauth/authorize";
        options.TokenEndpoint = "https://github.com/login/oauth/access_token";
        options.UserInformationEndpoint = "https://api.github.com/user";
        options.ClientId = "xxxxxxxxxxxxxxxxxxxxxxxx";
        options.ClientSecret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        options.CallbackPath = new PathString("/signin-github");
        options.Scope.Add("user");
        options.Scope.Add("user:email");
});
```

Any ideas ?

**Comment by Tratcher** [comment]
(No OWIN here... just ASP.NET 5.)
Start with our sample here: https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L118
And don't forget these:
https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L23
https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L30

**Comment by Haythem** [comment]
First of all, I want to thank you for this fast reply.
I added the missing configuration and still not working. The `_signInManager.GetExternalLoginInfoAsync()` returns null.

The weird thing here is that I can't find the OAuthOptions class (and some other classes and properties that belong the the Asp.Net.Security namespace). I'm using the beta7 version. I upgraded to beta8 and rc1 with no luck.

**Comment by PinpointTownes** [comment]
The error you're seeing is typically caused by the fact your identity has no `ClaimTypes.NameIdentifier` claim, which seems to be the case here since you're not using the `CreatingTicket` event to add one using the user information retrieved from GitHub's API (see https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L145-L151).

ASP.NET Identity 2/3 will always return null if no `ClaimTypes.NameIdentifier` can be found, so make sure to always add one.

FYI:  there's a GitHub social provider on aspnet-contrib that will automatically handle that, without requiring you to implement `CreatingTicket` : https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers.

The alpha1 version (for ASP.NET 5 beta7) can be found on NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.GitHub/

@Eilon any chance you'd accept a PR updating README.md to mention that additional OAuth2/OpenID2 providers can be found on aspnet-contrib?

**Comment by Eilon** [comment]
@PinpointTownes yeah we'd be happy to have links to good 3rd party projects such as your auth stuff. I use your GitHub auth and am quite happy with it! :smile:

**Comment by Haythem** [comment]
@PinpointTownes Thanks for your help on this.

What I wanted to do is something similar to your library. But it appears to be that the `Microsoft.AspNet.Security.OAuth` does not contain some classes and seems to be outdated (for some reason that I don't know at this point).

I'm closing this issue because your library just saved my day. Thanks one more time.

**Comment by PinpointTownes** [comment]
@Haythem you're welcome :clap: 

FYI, `Microsoft.AspNet.Security.OAuth` was renamed to `Microsoft.AspNet.Authentication.OAuth` many months ago, so if you're still the first package, you're probably referencing really old bits.

In beta8, most of the security classes have been renamed (basically, `Authentication` was removed from their name), so don't be surprising if you see a breaking change between beta7 and beta8 :+1:

**Comment by PinpointTownes** [comment]
@Eilon nice, thanks. I'll try to submit a PR for that :+1:
