### ISSUE TITLE
Stop using AuthenticateResult.Success(ticket: null)

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#555]
The whole new `AuthenticateResult.Success(ticket: null)` is used in multiple places (e.g https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L397 or https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L437)

Sadly, this doesn't seem to be a legal operation, as `Success` throws an exception when `ticket` is null: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication/AuthenticateResult.cs#L40

/cc @HaoK @Tratcher

**Comment by HaoK** [comment]
Yeah we should definitely be phasing those out...

**Comment by HaoK** [comment]
In the OIDC case, what does it actually mean to Skip a message, is that really a failure now in the new sense that no ticket is produced?

**Comment by HaoK** [comment]
Note: JwtBearer also has this usage still.

**Comment by PinpointTownes** [comment]
Ahah, I just had the same concern when updating ASOS. I simply decided to return null :smile: 

> In the OIDC case, what does it actually mean to Skip a message, is that really a failure now in the new sense that no ticket is produced?

I'm really tempted to say no. Actually, it wouldn't be an issue if the authenticate result wasn't a binary thing.

The cookies middleware suffers from the same symptom: I don't think returning a "failure" is semantically appropriate when no cookie was received: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationHandler.cs#L110

**Comment by HaoK** [comment]
Well we don't actually treat a "Failure" any differently than a success.  It just means there was no Ticket.  Its up to the caller to use the exception if desired.  In the cookies case, it doesn't care about errors, so it just calls context.Failed instead of the old NotAuthenticated, which is pretty much the same thing in that you get a result with no ticket.  Perhaps Success/Failure isn't the right names.  Its basically "Ticket/NoTicket" which is the definition for success/failure now...

**Comment by HaoK** [comment]
Previously we used to just return null or non null, which maps to Success/Failure, except we used to have a 'success' with no ticket which was a bit ambiguous.

**Comment by sunsided** [comment]
It is also in all of the JWT Token validation events where it absolutely doesn't matter if you call `context.HandledResponse()` with no ticket set (crashes due to `null` ticket) or call `context.SkipToNextMiddleware()` where it crashes because the caller code passes a `null` ticket explicitly.

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerHandler.cs#L74-L83
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerHandler.cs#L118-L127
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerHandler.cs#L151-L159

The last one is especially nasty because now there (finally, hah) is a place to return 401 errors in case of invalid tokens, but no matter what you do, it still throws an exception, resulting in a 500 instead ...

**Comment by Tratcher** [comment]
This is on me to create a sample and test for Skip so we can properly implement it across the stack.
