### ISSUE TITLE
Question about ITicketStore and ApplicationCookie.SessionStore injection

### ISSUE THREAD

**Issue by rustd** [aspnet/Security#581]
Moving this bug from https://github.com/aspnet/Identity/issues/624
@Schlurcher FYI

**Comment by jusbuc2k** [comment]
I'm running into the same issue trying to use a database connection, entity framework, etc. in my ticket store implementation. It seems like the setupAction parameter on the AddIdentity() service collection needs to provide an instance of IServiceProvider in a similiar manner to AddScoped(), AddTransient(), etc. does when using a function to create the service instance.

**Comment by jusbuc2k** [comment]
After looking at this more, it occurred to me that you can just register an IOptions<IdentityOptions>> *before* the call to AddIdentity() in order to get services as part of configuring identity options. For example:

```csharp
services.AddScoped<IOptions<IdentityOptions>>((sp) =>
            {
                var opts = new IdentityOptions();

                opts.Cookies.ApplicationCookie.SessionStore = new MyCustomDatabaseTicketStore(sp.GetService<ApplicationDbContext>());

                return Options.Create(opts);
            });

services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()                
                .AddDefaultTokenProviders();
```

This works because internally all the identity classes use the DI container/service provider to get IdentityOptions via dependencies on IOptions<IdentityOptions>.

**Comment by KolyaNET** [comment]
In the version of `Microsoft.AspNetCore.Identity 1.1.2`, I get an error when using `Microsoft.AspNetCore.Identity.UserManager.GenerateUserTokenAsync`

> NotSupportedException: No IUserTokenProvider named 'Default' is registered.

As soon as I comment on `services.AddScoped<IOptions<IdentityOptions>((sp) =>...` the error disappears and for example, resetting the password or confirming the email work correctly.

**Comment by izzyonstage** [comment]
If your `MyCustomDatabaseTicketStore` is registered for DI then you could use something similar to what is described here [https://andrewlock.net/access-services-inside-options-and-startup-using-configureoptions/]. This would allow options to be configured that use other DI entities rather than trying to wrap the options yourself.

Personally I have never liked adding `IOptions<T>` things to DI using the "Add..." methods. I have always added options using `services.Configure<T>(...)`. However, that does not have access to the ServiceProvider, so as shown in the link above there is the IConfigureOptions<T> mechanism that can be used to do this.

**Comment by Eilon** [comment]
@HaoK can you show the 2.0+ way of doing this?

**Comment by HaoK** [comment]
You should be able to just do
```
services.Configure<CookieOptions, ITicketStore>(IdentityDefaults.ApplicationCookie, o, store => o.SessionStore = new MyCustomDatabaseTicketStore(store))
```

**Comment by zerda** [comment]
I must missed some imports, @HaoK 's comment is not working for me.

In .Net Core 2.0, I'm using
```csharp
services.AddOptions<CookieAuthenticationOptions>(CookieAuthenticationDefaults.AuthenticationScheme)
    .Configure<ITicketStore>((options, store) => options.SessionStore = store);
```

**Comment by HaoK** [comment]
This overload only works in 2.1, in vanilla 2.0 you would have to implement an `IConfigureOptions<CookieAuthenticationOptions>` and have the constructor take `ITicketStore` and use the store in the implementation of Configure

**Comment by HaoK** [comment]
This one? https://github.com/aspnet/Options/blob/release/2.1/src/Microsoft.Extensions.Options/OptionsBuilder.cs#L57

**Comment by geirsagberg** [comment]
Yeah I'm using that one, but that is used like Zerda showed:
```
services.AddOptions<CookieAuthenticationOptions>(CookieAuthenticationDefaults.AuthenticationScheme)
    .Configure<ITicketStore>((options, store) => options.SessionStore = store);
```
Not like the example you suggested:
```
services.Configure<CookieOptions, ITicketStore>(IdentityDefaults.ApplicationCookie, o, store => o.SessionStore = new MyCustomDatabaseTicketStore(store))
```
No worries though, the former version is plenty good enough for me :)
