### ISSUE TITLE
Obtain dependencies through RequestServices, not through options

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Security#591]
I can see that dependencies like [`ITicketStore`](https://github.com/aspnet/Security/blob/409b50269a9d85618a31f84a3ffc2868abb3eeea/src/Microsoft.AspNet.Authentication.Cookies/ITicketStore.cs), [`ISystemClock`](https://github.com/aspnet/Security/blob/409b50269a9d85618a31f84a3ffc2868abb3eeea/src/Microsoft.AspNet.Authentication/ISystemClock.cs) are [being set through the options](https://github.com/aspnet/Security/blob/409b50269a9d85618a31f84a3ffc2868abb3eeea/src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationOptions.cs#L152) and I am not sure why they are not being set and requested through the [RequestServices](https://github.com/aspnet/HttpAbstractions/blob/67aa2546a87f0617005e6f5571ed7fed8ab2f088/src/Microsoft.AspNet.Http.Abstractions/HttpContext.cs#L61).

Besides this being the sensible approach, one legitimate reason is the below scenario: 
- I would like to replace `ITicketStore` with my own implementation and that implementation rely on another service which is scoped per http request inside the services collection.

**Comment by PinpointTownes** [comment]
:-1: for `ITicketStore` (as resolving it from the DI container would affect every instance of the cookies middleware in a same application) but :+1: for `ISystemClock` :smile:

**Comment by tugberkugurlu** [comment]
@PinpointTownes you have hit my second frustration: https://github.com/aspnet/HttpAbstractions/issues/492

To me, that should be the part that needs fixing too and `ITicketStore` should be retrieved from `RequestServices` unless there is another compelling reason.

**Comment by PinpointTownes** [comment]
This part is far trickier to "fix" than you might think :smile: 

We had a very interesting discussion with @MartinJohns a while ago about this specific question and we ended up creating a new set of extensions to support such scenarios (`Isolate` and `IsolatedMap`). https://github.com/aspnet-contrib/AspNet.Hosting.Extensions/blob/dev/src/AspNet.Hosting.Extensions/HostingExtensions.cs

We use `Isolate` in OpenIddict to run MVC 6 in an isolated environment, with its own options (that won't interfere with the default app options): https://github.com/openiddict/core/blob/dev/src/OpenIddict.Mvc/OpenIddictExtensions.cs#L51. 

Sadly, since it uses its own environment, using the services defined by the parent builder is not easy and we have to use some "services bridges" to make that work: https://github.com/openiddict/core/blob/dev/src/OpenIddict.Mvc/OpenIddictExtensions.cs#L97-L105

**Comment by tugberkugurlu** [comment]
@PinpointTownes yes, it's not easy to change this right now, I get that but it doesn't mean it shouldn't.

**Comment by Eilon** [comment]
`ISystemClock` is for internal testing purposes only and so we'll ignore that for now.

Regarding DI support in general, that's a good idea, but it's a very large change so we'll revisit this in a future release.

**Comment by HaoK** [comment]
We can revisit this now in 2.0, since Auth 2.0 has moved everything over to DI, ISystemClock for example is now a service.  We could do something similar for ITicketStore.  Clearing backlog for re-triage

**Comment by PinpointTownes** [comment]
> We could do something similar for ITicketStore.

Which would necessarily imply that you couldn't use a different store per scheme. A better approach would be to have both an option property and DI injection if the option property is null.

**Comment by Eilon** [comment]
It's not clear which items can really be services because some of them are auth-handler-specific, so resolving them from DI would prevent that. We'll have to see for which specific items this is actually possible.

**Comment by HaoK** [comment]
Consider making cookie validators services?

**Comment by HaoK** [comment]
Moving to 2.1 as this isn't critical for 2.0

**Comment by Eilon** [comment]
Closing because we are not planning on doing this.
