### ISSUE TITLE
Reminder to look at sugar for AuthorizationContext.Succeed

### ISSUE THREAD

**Issue by brockallen** [aspnet/Security#631]
For these scenarios:

```
public class AlbumEditHandler : AuthorizationHandler<OperationAuthorizationRequirement, Album>
{
    protected override void Handle(
        AuthorizationContext context,
        OperationAuthorizationRequirement requirement,
        Album resource)
    {
        if (requirement == AlbumAuthorization.Edit)
        {
            if (context.User.IsInRole("Employee") ||
            context.User.FindFirst("username").Value == resource.Owner)
            {
                context.Succeed(requirement);
            }
        }
    }
}
```

and this:

```
config.AddPolicy("PayingCustomer", builder =>
{
    builder
        .RequireAuthenticatedUser()
        .RequireClaim("role", "Customer")
        .RequireDelegate((ctx, r) =>
        {
            var endDateClaim = ctx.User.FindFirst("SubscriptionEndDate");
            if (endDateClaim != null)
            {
                var endDate = DateTime.Parse(endDateClaim.Value);
                if (DateTime.Now <= endDate)
                {
                    ctx.Succeed(r);
                }
            }
        });
});
```

**Comment by HaoK** [comment]
cc @blowdart 

So we don't have many great options here, the issue is that at the lowest level, handlers are working against a context, which have arbitrarily many requirements.  Its only the handler 'sugar' that we've added that starts passing around specific requirements.  

Its perfectly valid for a handler to succeed more than the specific requirement that was asked for.

One example would be maybe there's a BackdoorRequirementHandler that would let certain users bypass everything.  And he could `context.Succeed()` all requirements, not just the current one.

We could add sugar to purely hide succeed and instead return a bool.  And if you wanted to do other stuff to the context you still can.  Returning true would just automatically succeed the requirement for you.

```
   protected abstract bool CheckRequirement(AuthorizationContext context,
        TRequirement requirement,
        TResource resource);

   protected virtual void Handle(AuthorizationContext context,
        TRequirement requirement,
        TResource resource) {
       if (CheckRequirement(context, requirement, resource)) {
           context.Succeed(requirement);
       }
   }

```

I'm definitely open to any other suggestions on how we could improve this, but at the end of the day this is the one and only core responsibility of the handler: calling context.Succeed(requirement).  I don't love this sugar as we are basically replacing the explicit operation with a magic bool where stuff happens if you return true, but if you guys like it, I can live with it...

**Comment by HaoK** [comment]
cc @divega @lodejard for thoughts on whether this is sugar overkill... 

To summarize: Should we add overloads to register a `Func<AuthorizationContext, TRequirement, resource, bool>` in general to paper over the context.Succeed(requirement) mechanic...

**Comment by blowdart** [comment]
So calling context.Succeed() to pass everything is, to my mind, going to be a pretty rare case. @brockallen what's your opinion? Would you use that anywhere?

I'm actually a little concerned that someone would forget to pass in the requirement and succeed everything. To my mind it'd be better to make the default "Succeed the current requirement" and then have a specific way to do the "backdoor" scenario.

**Comment by brockallen** [comment]
First of all, being a Microsoft employee I'd recommend against using an example like `BackdoorRequirementHandler`. Who knows how it would be taken out of context. :)

As for the sugar, maybe it gets too confusing to have too many different ways to do it. If it starts to feel too contrived to do it, then I'd skip it -- no worries.

**Comment by blowdart** [comment]
Yea, we should use nsakeyRequirementHandler instead :D

**Comment by HaoK** [comment]
Ok I will skip this for now we can always add more sugar later if we get more feedback about this.

**Comment by blowdart** [comment]
I think you should do something about .Succeed() overriding everything. That is too easy to screw up. People will do that by default and wonder why things are succeeding when other requirements don't.

**Comment by HaoK** [comment]
There's no such thing as succeed that takes nothing today.

**Comment by HaoK** [comment]
Moving this to backlog for now

**Comment by HaoK** [comment]
The RequireAssertion that returns a bool sugar addresses this I think
