### ISSUE TITLE
Why is Microsoft.AspNetCore.Authentication.OpenIdConnect on version 0.1.0?

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Security#738]
Hi, Currently `Microsoft.AspNetCore.Authentication.OpenIdConnect` has the version number `0.1.0-*`. Almost every other package has `1.0.0-*`. Is this intentional? Won't it be finished for V1?

**Comment by Eilon** [comment]
@cwe1ss sorry for the delay getting back to you.

This package, along with a few other packages (such as the SignalR packages), have been marked as version 0.1.0 to indicate that we are less certain it will be at the quality level needed to consider it an "RTM" release.

The main reason this package is in that state is that it has had relatively little usage, and relatively little feedback, so we are less certain that it necessarily meets the needs of its users. It is also a relatively newer codebase compared to some other providers, so it has a lot less history to work off of.

We are still committed to *shipping* it, but because it's not currently planned to be in an "RTM" quality level, it might still have breaking changes in it.
