### ISSUE TITLE
AuthorizationContext questions - Fail scenarios and non-async code

### ISSUE THREAD

**Issue by slaneyrw** [aspnet/Security#784]
Backgound - I'm "forward" patching the authorization framework into our existing ASP.NET 5 MVC and have some questions regarding the Authorization assembly/system

The Fail method and HasFailed property on the AuthorizationContext class do not appear to be used.  Is it your intention that failing to call success for a requirement constitutes as a policy failure ?

The backing store **_failedCalled** set when Fail() is invoked is tested in the HasSucceeded property making the HasFailed property redundant ?

There also appear to be no unit tests around the use of AuthenticationContext.Fail

Further more that also appear to be no tests around the synchronous paths of the Authorization handlers, and I can't find any invocation of the non-async version.  Is the non-async part of Authorization system redundant and will be removed ?

**Comment by MonkeyJamboree** [comment]
I noticed the sync/async weirdness with the handlers as well. Particularly the fact that `IAuthorizationHandler` exposes `HandleAsync` but not `Handle`, however the `AuthorizationHandler<TRequirement>` class provides both sync and async functionality. It seems that it may be prudent to either add sync functionality to the interface (or provide a secondary interface that does so) and make the `Handle` method virtual, or to only provide async functionality and let consumers handle it how they require.

**Comment by muratg** [comment]
@HaoK Could you have a look?

**Comment by Eilon** [comment]
Ping @HaoK

**Comment by HaoK** [comment]
@MonkeyJamboree The core API is intended to be fully async,, which is why `IAuthorization` only has async methods.  The sync versions are added only as sugar in the helper base class as convenience. 

@slaneyrw Fail is basically a veto method, its not normally needed to be called as if all requirements are not successfully met, the default behavior is to fail.  But a handler wants to fail the authorization request regardless of the status of any other requirements, that is what Fail is meant to accomplish, it overrides and causes the Authorize to fail with no way to undo.

**Comment by Eilon** [comment]
BTW we have some docs on this as well: https://docs.asp.net/en/latest/security/authorization/policies.html#what-should-a-handler-return
