### ISSUE TITLE
Project Microsoft.AspNetCore.Authentication does not have a lock file

### ISSUE THREAD

**Issue by gabrielacosta** [aspnet/Security#869]
I was trying to test the samples in the security package. I keep getting this error 
Project.AspNetCore.Authentication does not have a lock file
when I try to run any example. 
Could you please tell me how to fix it.

**Comment by gabrielacosta** [comment]
Sorry, I open the entire solution and the lock error is not appearing anymore. Now, I have this issue.

C:\JuanStuff\Code\Mono\Security\samples\SocialSample>dotnet restore
log  : Restoring packages for C:\JuanStuff\Code\Mono\Security\samples\SocialSample\project.json...
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.netcore.platforms/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.NETCore.Platforms'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.aspnetcore.http/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNetCore.Http'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.aspnetcore.http.extensions/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http.extensions/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNetCore.Http.Extensions'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.logging.abstractions/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.abstractions/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Extensions.Logging.Abstractions'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.options/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.options/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Extensions.Options'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.webencoders/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Extensions.WebEncoders'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.aspnetcore.dataprotection/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.dataprotection/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNetCore.DataProtection'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.aspnetcore.server.iisintegration/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.iisintegration/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNetCore.Server.IISIntegration'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.aspnetcore.server.kestrel/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.kestrel/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNetCore.Server.Kestrel'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.aspnetcore.server.kestrel.https/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.kestrel.https/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNetCore.Server.Kestrel.Https'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.configuration.usersecrets/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.usersecrets/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Extensions.Configuration.UserSecrets'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.fileproviders.embedded/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.fileproviders.embedded/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Extensions.FileProviders.Embedded'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.logging.console/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.console/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Extensions.Logging.Console'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.configuration.environmentvariables/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.environmentvariables/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Extensions.Configuration.EnvironmentVariables'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/system.net.http/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.net.http/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Net.Http'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/system.runtime.serialization.primitives/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.runtime.serialization.primitives/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Serialization.Primitives'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.netcore.app/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.NETCore.App'
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/libuv/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/libuv/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Libuv'
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in C:\JuanStuff\Code\Mono\Security\samples\SocialSample\project.json...
info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.aspnetcore.server.iisintegration.tools/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.iisintegration.tools/index.json
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNetCore.Server.IISIntegration.Tools'
error: Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-002966 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-002966 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netstandard1.6 (.NETStandard,Version=v1.6)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
info : Committing restore...
log  : Lock file has not changed. Skipping lock file write. Path: C:\JuanStuff\Code\Mono\Security\samples\SocialSample\project.lock.json
log  : C:\JuanStuff\Code\Mono\Security\samples\SocialSample\project.json
log  : Restore failed in 2120ms.

Errors in C:\JuanStuff\Code\Mono\Security\samples\SocialSample\project.json
    Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-002966 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-002966 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

NuGet Config files used:
    C:\JuanStuff\Code\Mono\Security\NuGet.Config
    C:\Users\juan\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://www.myget.org/F/aspnetcidev/api/v3/index.json
    https://api.nuget.org/v3/index.json
    https://www.nuget.org/api/v2/
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

I quite confused. I just installed this compilation for test dotnet in Centos.  
https://www.microsoft.com/net/core#centos

I appreciate any help.

**Comment by Tratcher** [comment]
What happens if you run the build.sh script in the root `Security\` directory?

**Comment by gacostab** [comment]
I tried the build and it when fine until this...

Project OpenIdConnect.AzureAdSample (.NETFramework,Version=v4.5.1) will be compiled because expected outputs are missing
Compiling OpenIdConnect.AzureAdSample for .NETFramework,Version=v4.5.1
C:\Users\juan\AppData\Local\Microsoft\dotnet\dotnet.exe compile-csc @C:\JuanStuff\Code\Mono\Security\samples\OpenIdConnect.AzureAdSample\obj\Debug\net451\dotnet-compile.rsp returned Exit Code 1
C:\JuanStuff\Code\Mono\Security\samples\OpenIdConnect.AzureAdSample\Startup.cs(90,52): error CS1501: No overload for method 'Encode' takes 4 arguments

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:01.2795444

Project OpenIdConnect.AzureAdSample (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling OpenIdConnect.AzureAdSample for .NETCoreApp,Version=v1.0
C:\Users\juan\AppData\Local\Microsoft\dotnet\dotnet.exe compile-csc @C:\JuanStuff\Code\Mono\Security\samples\OpenIdConnect.AzureAdSample\obj\Debug\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1
C:\JuanStuff\Code\Mono\Security\samples\OpenIdConnect.AzureAdSample\Startup.cs(90,52): error CS1501: No overload for method 'Encode' takes 4 arguments

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:01.0944722

Project OpenIdConnectSample (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project OpenIdConnectSample (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Project SocialSample (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project SocialSample (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
fail: Exit code 1 from dotnet
fail: Stack trace:
   at View0d152910bfef43da96e545d7b2343a00.Dotnet(String command) in c:\Users\juan\AppData\Local\Temp\601064f984364a9d9714bdbefc4b9ffe-1.cs:line 1071
   at View0d152910bfef43da96e545d7b2343a00.DotnetBuild(String projectFile, String configuration, String framework) in c:\Users\juan\AppData\Local\Temp\601064f984364a9d9714bdbefc4b9ffe-1.cs:line 1308
   at View0d152910bfef43da96e545d7b2343a00.<>c__DisplayClasse7.<RenderViewLevel0>b__ab() in c:\Users\juan\AppData\Local\Temp\601064f984364a9d9714bdbefc4b9ffe-1.cs:line 9559
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View0d152910bfef43da96e545d7b2343a00.StartingTarget(String name) in c:\Users\juan\AppData\Local\Temp\601064f984364a9d9714bdbefc4b9ffe-1.cs:line 3593
   at View0d152910bfef43da96e545d7b2343a00.<RenderViewLevel0>b__64() in c:\Users\juan\AppData\Local\Temp\601064f984364a9d9714bdbefc4b9ffe-1.cs:line 4040
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View0d152910bfef43da96e545d7b2343a00.StartingTarget(String name) in c:\Users\juan\AppData\Local\Temp\601064f984364a9d9714bdbefc4b9ffe-1.cs:line 3593
   at View0d152910bfef43da96e545d7b2343a00.<RenderViewLevel0>b__65() in c:\Users\juan\AppData\Local\Temp\601064f984364a9d9714bdbefc4b9ffe-1.cs:line 4057
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View0d152910bfef43da96e545d7b2343a00.StartingTarget(String name) in c:\Users\juan\AppData\Local\Temp\601064f984364a9d9714bdbefc4b9ffe-1.cs:line 3593
   at View0d152910bfef43da96e545d7b2343a00.<RenderViewLevel0>b__66() in c:\Users\juan\AppData\Local\Temp\601064f984364a9d9714bdbefc4b9ffe-1.cs:line 4074
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at View0d152910bfef43da96e545d7b2343a00.<RenderViewLevel0>b__5e() in c:\Users\juan\AppData\Local\Temp\601064f984364a9d9714bdbefc4b9ffe-1.cs:line 3930
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by PinpointTownes** [comment]
Your clone is probably a bit old now, and doesn't include the latest commits. Specially this one: https://github.com/aspnet/Security/commit/33b69c14edda3d96bc489e74a8ecf8d98f55ef25

Rebase your local branch or re-clone this repository and this error should disappear.

**Comment by Tratcher** [comment]
Ah, you caught me half way through a minor breaking change. The updated packages should be available now.

**Comment by Tratcher** [comment]
Closing this for now. Let us know if you have any additional issues.
