### ISSUE TITLE
FaceBook/LinkedIn authentication for ASP.NET Core WebAPI

### ISSUE THREAD

**Issue by GKersten** [aspnet/Security#900]
I've created a ASP.Net Core MVC project with individual user accounts and added FaceBook authentication. Now I also want to use this FaceBook authentication for my WebAPI, any samples on how to do this? Also interested in extending this with LinkedIn authentication.

**Comment by Tratcher** [comment]
@blowdart do we have any concept docs for this FAQ?

**Comment by blowdart** [comment]
Nope, this would really mean the browser doing the oauth pieces using their SDK, and then straightforward JWT. Our exchanging for a cookie, which is what we do for forms isn't probably what you want.

**Comment by brockallen** [comment]
It means you need a token service which performs the federation to facebook, but then issues a token for your own API.

**Comment by GKersten** [comment]
@blowdart alright, I'm trying to create a WebAPI that will be consumed by a native/Xamarin mobile app. So as I understand, the way to go is do Oauth client side with Facebook/LinkedIn SDK and than JWT authentication with my Web API?

**Comment by brockallen** [comment]
You need a token service for you APIs and when the user logs into it via the browser it supports facebook logins. IdentityServer4 supports that scenario: https://github.com/IdentityServer/IdentityServer4

**Comment by blowdart** [comment]
Yup. As @brockallen says Identity Server does the work for you. I'd strongly recommend looking at that, rather than trying to roll your own. Identity Server does the auth & validation, and then issues you a token for your own app, rather than doing it in javascript, which would be the alternative.

**Comment by cwe1ss** [comment]
@blowdart @brockallen @leastprivilege but if we use IdentityServer, our app would no longer get the original Facebook token, so we couldn't query the Facebook API for additional stuff etc. It would also mean, that the app must use a webview-based login screen instead of a native one (because IdentityServer is displaying it), right?

how would this work if I wanted to have a native login screen and keep the facebook token in my app - e.g. like the Spotify app (at least I think it's a native screen :smile:):

![spotify-login-small](https://cloud.githubusercontent.com/assets/4581460/17215500/572d244c-54dd-11e6-956e-7d3d963b3b56.jpg)

If the user enters username/password, I would call my IdentityServer4 token endpoint with the "resource owner password credentials grant" and would get my own token, right?

But with the Facebook Login button, my native app would start the login process and it would get back the facebook access token. It could now call the Facebook API etc.

To call my own API, could I use the token endpoint of IdentityServer4 to exchange the token? Would the following flow be possible/secure:

* native app starts Facebook Login process and aquires valid facebook access token
* native app sends request to IdentityServer4 token endpoint with "grant_type=password&username=external:facebook&password=facebook-access-token". 
  * the username would be a reserved name just for this purpose
  * the alternative would be a custom grant_type
* IdentityServer4 has the same facebook app credentials as the native app and validates the token
* IdentityServer4 looks up a user account with the given facebook userid
* IdentityServer4 returns a new access token
* native app sends the access token to my backend API

**Comment by brockallen** [comment]
You will still need to use a browser flow so the user can login to facebook. IdSvr becomes the client of facebook and you can do whatever you want to there w/ the FB token.

**Comment by cwe1ss** [comment]
Thanks for your answer, Brock! I have a few more questions and I would really appreciate further feedback from you!

My main concern was that web UIs in native apps don't share cookies with Safari (iOS) or Chrome (Android), so users would have to enter their Facebook password again (which is really annoying). The native Facebook SDK would have allowed to use "app switching" to authenticate directly with the installed Facebook app and only fallback to a web view if it's not installed.

However, I've just read that iOS 9 introduced the "Safari View Controller" which *does* share cookies with Safari. Seems like even the Facebook SDK now [uses this model by default](https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/).

Android seems to have a similar model with "[Chrome Custom Tabs](https://developer.chrome.com/multidevice/android/customtabs)" which is supported since 4.1 (Jelly Bean) and Chrome 45.

So it seems like going with a web UI is ok!

I still would like to have one native screen (more beautiful, I don't want to open the Web UI popup immediately, ...) that looks like this:

![hubbl-login](https://cloud.githubusercontent.com/assets/4581460/17223890/d45c465c-54fe-11e6-89fd-8508847e5d2d.jpg)

Does IdentityServer4 have a built-in parameter (e.g. "provider=facebook") in its authorize endpoint to immediately start the authentication process with this provider or would I have to implement this myself?

This would be my updated flow:

* Native app displays native screen with buttons (see above)
* User clicks on "Connect with Facebook"
* App opens Web UI and calls IdentityServer4 authorize endpoint
* IdentityServer immediately redirects to Facebook
* User authenticates with Facebook and authorizes the app
* IdentityServer gets the token
* IdentityServer looks up the user in its database (based on facebook user-id). If none found, it may immediately create one
* IdentityServer does another Facebook API call to exchange the short-lived token with a long-lived token (60 days) and stores it e.g. as a claim
  * Facebook tokens aquired by native apps are long-lived (valid for 60 days), tokens aquired by web apps (like IdentityServer) are short-lived.
* IdentityServer creates its own token and adds the facebook access token as a claim to its token.
* IdentityServer sends its token to native app
* The native app can now use the IdentityServer-token to call our backend API and the facebook access token to call the Facebook API

One thing I'm concerned about is how the Facebook access token will be refreshed in this scenario. Since the app now only requests IdentityServer tokens, there wouldn't be any further calls to Facebook, right?

Would I have to extend the IdentityServer token endpoint to also periodically fetch new Facebook access tokens when new IdentityServer tokens are aquired?

**Comment by cwe1ss** [comment]
Or should the native app refresh the facebook access tokens by calling the Facebook API directly? This way, IdentityServer probably wouldn't even have to store them?!

**Comment by brockallen** [comment]
> My main concern was that web UIs in native apps don't share cookies with Safari (iOS) or Chrome (Android)

Depends. You can use the in-app browser tab. I'm on holiday so I'll get in trouble if I spend too much time on the issue tracker, but search for Dom's securing mobile apps video from NDC Oslo this past summer.

**Comment by cwe1ss** [comment]
no worries, enjoy your holiday!!! :smile:

**Comment by cwe1ss** [comment]
I guess, I found it. Thanks!

[Authentication & secure API access for native & mobile Applications - Dominick Baier](https://vimeo.com/171942749) - in case someone else is interested

**Comment by tinchou** [comment]
I'm also working on a similar problem. I'm using JWT as my app's authentication transport method, and the users get one after signing in with their username and password.

On the other hand, they can also use Facebook to authenticate.

`FacebookAuthenticationMiddleware` does a nice work validating Facebook's access_token and also populating the user claims with it. It does almost everything [here](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Facebook/FacebookHandler.cs). There's also other validation steps (like the `state` parameter) going on [here](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OAuth/OAuthHandler.cs#L55).

My main issue is that I'd need to redo (ahem, *copy and paste*) all your work in order to implement a `/token/facebook` or similar endpoint which would receive the access_token (instead of the username and password) and issue the JWT. I've seen an implementation use [the Facebook .NET SDK](https://www.nuget.org/packages/Facebook) to validate, but for starters it doesn't target the Core framework.

I thought about writing a middleware that would manually call Facebook authentication but I can't make it work. The `AuthenticateAsync` call throws `InvalidOperationException: No authentication handler is configured to authenticate for the scheme: Facebook`:

```cs
if (context.Request.Path.Equals("/signin-facebook", StringComparison.Ordinal))
{
    var user = await context.Authentication.AuthenticateAsync(FacebookDefaults.AuthenticationScheme);
}
```

**Comment by Tratcher** [comment]
Look at the Individual Auth template in VS where you can log in with OAuth providers (Facebook) or username and password. If you already have the logic to issue JWTs for user logins, you should be able to use the existing middleware to log in and then issue a JWT from there. See https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Controllers/AccountController.cs#L149-L234

**Comment by tinchou** [comment]
Thanks for your reply! I looked at it but I think it's too tied into how
the template sets up authentication. For example, I'm not using Identity
but only the jwt authentication middleware.

My solution for now is to get an access token in the client side using the
Facebook SDK. Then validate it with a custom code derived from
FacebookHandler code and generate the jwt.

**Comment by norcis** [comment]
Hi everybody! I have the same concerns web UI vs native UI with "resource owner password credentials grant" and social login. As I understand web UI is recommended way. What is your experience going one or another way?

**Comment by alexidsa** [comment]
Could anyone please explain me why keeping OAuth token and working with it without  JWT layer was never considered as an option in this thread?

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by softlion** [comment]
Hi there, you say there is no action planned, but a planned action could be writing a doc on how to answer the question WITHOUT using the web ui, but the native SDK ones, which IS the way to go. Actually the only answer is to create a custom endpoint which receives the provider specific data, uses the existing middlewares to validate them, store them, and exchange them for a valid app's JWT.

It is a common problem, so it needs a common answer. 

See my question here https://stackoverflow.com/questions/44523234/how-to-authenticate-to-a-custom-oauth2-server-using-an-existing-facebook-login-t

**Comment by Eilon** [comment]
@softlion sorry for the delay, I was traveling. We have some work planned for our 2.1 version that should make it easier to use OIDC for Web API auth.

**Comment by softlion** [comment]
What is OIDC ?
I tried the approach I described and it works fine. Validated the signed jwt tokens using google and Facebook sdks.

**Comment by brockallen** [comment]
> What is OIDC ?

OpenID Connect: http://openid.net/connect/
