### ISSUE TITLE
Get AuthenticationSchemes used to sign the user in

### ISSUE THREAD

**Issue by dstrockis** [aspnet/Security#911]
Long story short: for Azure AD B2C, we need to use multiple instances of the OIDC middleware in a single app.  On signout, I want to send a sign out request only for the instance(s) of the OIDC middleware that have been used to sign the user in.

In Katana I could enumerate thses instances by doing `HttpContext.GetOwinContext().Authentication.GetAuthenticationTypes()`.

In core when I do `HttpContext.Authentication.GetAuthenticationSchemes();` I get back several more schemes than we used to sign the user in, including `NTLM` and `Negotiate`.

Doing `User.Identity.AuthenticationType` gets me `AuthenticationTypes.Federation`.

Happy to provide sample code if necessary.  And if you wouldn't mind, please tag (@) me in any responses you want me to see so I can keep track.

**Comment by Eilon** [comment]
It seems you can call https://github.com/aspnet/Identity/blob/ec4c08d11a00ec9b4dd8c22ef13a4950cb70901e/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L432 to get the authentication schemes that are "interactive." It appears that they're already filtered in this API because it excludes ones that don't have a Display Name.

**Comment by dstrockis** [comment]
Closing this for now, since I have a workaround for my particular scenario.
